### ISSUE TITLE
Cannot read property Aspect of undefined

### ISSUE THREAD

**Issue by Sumanthjois** [react-native-camera/react-native-camera#1117]
I am trying import Camera to my app and I followed the installation instructions in the document. But build fails and I am getting the following error:

`Cannot read property Aspect of undefined`

### Below is my code
```
'use strict';
import React, { Component } from 'react';
import {
  View,
  Text,
  StyleSheet,
  Dimensions,
} from 'react-native';
import Camera from 'react-native-camera';
export default class GetCard extends Component {


  static navigationOptions = {
    title: 'Get Card',
  };

  onQRCodeRead = (event) => {

  }

  render() {
    return (
      <View style={styles.container}>

      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  preview: {
   flex: 1,
   justifyContent: 'flex-end',
   alignItems: 'center'
 },
})
```

As you can see I am not even rendering the camera. I referred a similar type of issue but I couldn't find any solutions.

### Environment
- Node versions - v9.3.0
- React Native version - 0.51.0
- IOS 11

### react-native-camera
react-native camera version = 0.6

**Comment by sibelius** [comment]
you need react-native link

follow the readme instructions

**Comment by Sumanthjois** [comment]
I did run `react-native link react-native-camera `right after the installation but still, I am facing the issue. Like I have mentioned I have gone through readme instructions

**Comment by sibelius** [comment]
try to do this console.log(NativeModules)

and see if there is a Camera module there

if not the link is wrong

**Comment by egunsoma** [comment]
I also have this error, works fine on freshly generated project, but when I try to add the project to my existing one, with cocoapods & react-native-firebase, it throws this error, before running pod install. If I run pod install, countless errors appear, for me it seems like react-native-camera is installing another react-native. 

Any suggestions how to solve this?
when printing native modules, the Camera is not among the modules.

**Comment by alexey-belous** [comment]
```pod install``` after ```react-native link react-native-camera``` solves the issue for me.

**Comment by michaelmika** [comment]
I m also struggling with this. Did `link` and added to pod-file and did `pod install`. If I want to relink it says it is already linked. But I do not see `react-native-camera`(or anything with camera) in my xcode (not in libraries and not in linked frameworks) or at the printout of `console.log(NativeModules)`. So obviously it is not linked properly, or is it? But it builds successfully. Also using cocoapods (and hating it, causes many times problems) and react-native-firebase (same as @egunsoma ). 

My Cocoapod file looks as the following:

```
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'project' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for webcardlink
  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'DevSupport',
    'BatchedBridge', # Required For React Native 0.45.0+
    'Core',
    'RCTText', 
    'RCTImage', 
    'RCTNetwork', 
    'RCTWebSocket'
  ]
  # pod 'RNFirebase', :path => '../node_modules/react-native-firebase'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  # pod 'RSKImageCropper'
  # pod 'QBImagePickerController'  
  # pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob' 

  # pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'
  # pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'




  # pod 'RNFS', :path => '../node_modules/react-native-fs'

  # pod 'RNShare', :path => '../node_modules/react-native-share'

  # pod 'react-native-contacts', :path => '../node_modules/react-native-contacts'

  pod 'RNImageRotate', :path => '../node_modules/react-native-image-rotate'

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  target 'projectTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'project-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for project-tvOS

  target 'project-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# very important to have, unless you removed React dependencies for Libraries 
# and you rely on Cocoapods to manage it
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
```

But I have to admit I also imported modules manually (because, as I mentioned, hate them, or I did not get them).

**Comment by pulyavin** [comment]
If you using rn-camera v 1.0.1 with pods, you must:

in file `node_modules/react-native-camera/react-native-camera.podspec` change 
`s.source_files = 'ios/*.{h,m}'`

to

`s.source_files = 'ios/**/*.{h,m}'`

or updates to version 1.0.2

**Comment by michaelmika** [comment]
Thanks for your answer, it helped! But now I have the issue
```
react-native-camera/RNFaceDetectorManager.h:11:9: 'GoogleMobileVision/GoogleMobileVision.h' file not found
```

I haven't installed GMV, also do not plan to, in the docs it says `The face detection code is excluded by default for the CocoaPods installation.`

Also delete folder `FaceDetector`(which I only found at `Pods/Development Pods/react-native-camera`, RNCamera is still not listed in `project/Libaries`) but this did not help. Any suggestions?

**Comment by pulyavin** [comment]
Remove folder `node_modules/react-native-camera/ios/FaceDetector` and make sure that the folder FaceDetector has been deleted from your xcode project

**Comment by mashwinprdxn** [comment]
In case anyone's facing this issue on Android, please try the [gradle upgrade guide](https://github.com/react-native-community/react-native-camera/blob/master/docs/GradleUpgradeGuide.md). It worked for me.

**Comment by anhdevit** [comment]
> try to do this console.log(NativeModules)
> 
> and see if there is a Camera module there
> 
> if not the link is wrong

nice bro

**Comment by harrie006** [comment]
For me libRNCamera.a was not linked under link binary under build phases.
