### ISSUE TITLE
RNCamera blank preview on Android 4.4

### ISSUE THREAD

**Issue by almost** [react-native-camera/react-native-camera#1478]
Working from master I'm having an issue with older versions of android. Not working on my Android 4.4.4 device and my 4.4.2 one but it's working fine on my 7.0 device.

Preview view is just black. I see this on logcat:

```
W/CameraService(  176): CameraService::connect X (pid 6106) rejected (existing client with higher priority).
W/CameraBase( 6106): An error occurred while connecting to camera: 0
```

And when try to capture I get "Camera is not running".

Any thoughts of workarounds or ways to debug this? Does anyone else have it running on Android 4.4?

**Comment by almost** [comment]
Probably the same issue: https://github.com/expo/expo/issues/975

**Comment by almost** [comment]
Also mentioned here: https://forums.expo.io/t/black-screen-for-camera/3587/11

**Comment by sibelius** [comment]
this could be a nice tip to be in docs/Recipes

**Comment by sibelius** [comment]
or Q&A
