### ISSUE TITLE
`compileOnly` introduces gradle 3 dependency

### ISSUE THREAD

**Issue by vicapow** [react-native-camera/react-native-camera#1483]
Hello,

Just spent some time debugging this. so wanted to share my learnings in case anyone else runs into a similar issue. Looks like the `compileOnly` syntax introduced in https://github.com/react-native-community/react-native-camera/commit/1c7f231af460127bebf1f9970367bf64987de34b means folks need to upgrade their projects to gradle 3.

That will involve changing buildscript -> dependencies -> classpath to something like `'com.android.tools.build:gradle:3.0.1'`

````
buildscript {
    repositories {
        jcenter()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'
       // ...
````

When I did that I started getting errors about some modules not expecting some version of com.android.support.

````sh
> Android dependency 'com.android.support:exifinterface' has different version for the compile (25.4.0) and runtime (27.1.0) classpath. You should manually set the same version via DependencyResolution
````

Adding this bit fixed it for me:

````
subprojects {
  project.configurations.all {
     resolutionStrategy.eachDependency { details ->
        if (details.requested.group == 'com.android.support'
              && !details.requested.name.contains('multidex')
        ) {
           details.useVersion "27.1.0"
        }
     }
  }
}
````

Hope that helps others!

**Comment by prashantham** [comment]
Hi @sibelius , where is it mentioned in the docs?

**Comment by MLDimitry** [comment]
@sibelius It's not in the docs. Stop closing these **legitimate** issues anyone trying to use the latest 1.1.1 is getting this

**Comment by sibelius** [comment]
@MLDimitry you can follow react-native-maps docs for now

feel free to send a PR improving the docs
