### ISSUE TITLE
autoFocusPointOfInterest not implemented in RNCamera

### ISSUE THREAD

**Issue by msageryd** [react-native-camera/react-native-camera#1888]
I tried to implement autoFocusPointOfInterest in my app, but it didn't work.

After digging into the RNCamera code I found that this prop isn't implemented at all. I could give it a stab, but I have never worked with ObjC before. If someone could give me some hints on how to send JS objects over the bridge I might be able to pull this off.

**Comment by msageryd** [comment]
Oh, I'm sorry. I looked in a project which had RNCamera 1.20. autoFocusPointOfInterest was implemented in 1.30.

**Comment by jasan-s** [comment]
@msageryd  how are you getting the coordinate values to use in `autoFocusPointOfInterest`. can you share the implementation gist

**Comment by trinhlk31** [comment]
@msageryd Could you please share the code of "renderFocusPointOfInterest" function? Many thanks!

**Comment by ShawalAhmadPF** [comment]
for renderFocusPointOfInterest
you can apply :
```
renderFocusPointOfInterest =() =>{
        return <View style={{ position:'absolute', top:touchPosition.x*Imageheight, left:touchPosition.y*ImageWidth, height:20, width:20, borderWidth:1, borderColor:'#fff' }} ></View>
}
```
