### ISSUE TITLE
Android will crash on recordAsync() if captureAudio is not passed to RNCamera. It is not in the documentation

### ISSUE THREAD

**Issue by yernandus** [react-native-camera/react-native-camera#2030]
# Bug Report
**To Do First**
- [ x] Did you try latest release?
- [ ] Did you try master?
- [x ] Did you look for existing matching issues?

**Related Modules**

RNCamera

**Platforms**

Android

**Versions**

- Android: 8
- react-native-camera:1.6.2
- react-native:0.57.5
- react:16.6.1

**Description/Current Behaviour**

crash on recording video
**Expected Behaviour**

record a video
**Steps to Reproduce**

**Additionals**

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate
> Want this issue to be resolved faster? Please consider adding a bounty to it https://issuehunt.io/repos/33218414

**Comment by Rohithzr** [comment]
@n1ru4l related recursion overload :D

related #2025  ?

but I do have permissions.
I take permissions manually at the start of the app.

```
String[] perms = {
            "android.permission.WRITE_EXTERNAL_STORAGE",
            "android.permission.CAMERA",
            "android.permission.ACCESS_FINE_LOCATION",
            "android.permission.RECORD_AUDIO",
};
```
so these are 100% granted.

manifest.xml
```
<uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.RECORD_AUDIO"/>
    <uses-permission android:name="android.permission.RECORD_VIDEO"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission-sdk-23 android:name="android.permission.VIBRATE"/>
    <uses-feature android:name="android.hardware.camera" android:required="false" />
    <uses-feature android:name="android.hardware.camera.front" android:required="false" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
```

**Comment by n1ru4l** [comment]
Can you reproduce this issue with the example app in this repository?
