### ISSUE TITLE
Ratio not working in RNCamera.

### ISSUE THREAD

**Issue by ghost** [react-native-camera/react-native-camera#2076]
# Question

**To Do First**
- [x] Take a look in the [README](https://github.com/react-native-community/react-native-camera/blob/master/README.md)
- [x] Take a look in the [docs](https://github.com/react-native-community/react-native-camera/blob/master/docs/RNCamera.md)
- [x] Take a look in the [QA](https://github.com/react-native-community/react-native-camera/blob/master/docs/QA.md)

**Ask your Question**

I'm recording video in `react-native-camera` and when I display my video in `react-native-video` I'm unable to fit the video into view.

    <RNCamera
          ref={ref => { this.camera = ref; }}
          captureAudio={true}
          style={styles.preview}
          type={RNCamera.Constants.Type.back}
          permissionDialogTitle={'Permission to use camera'}
          permissionDialogMessage={'We need your permission to use your camera phone'}
      />

I've used the `ratio` option in RNCamera. I used `ratio={"1:1"}` and also `ration={"4:3"}` but I'm unable to get the desired results. Can someone please tell me how to use `ratio` ?

I've also tried the solution by Fconstant from this question. https://github.com/react-native-community/react-native-camera/issues/1280

**Tags**

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate
> Want this issue to be resolved faster? Please consider adding a bounty to it https://issuehunt.io/repos/33218414

**Comment by Udbhav12** [comment]
@shubham6996 : Did you manage to solve this?

**Comment by shubham6996** [comment]
@Udbhav12 No, I wasn't able to.

**Comment by billouboq** [comment]
Any update ? Having the same problem

**Comment by shubham6996** [comment]
@billouboq nope. Wasn't able to do it.

**Comment by sibelius** [comment]
check latest version

**Comment by Talha-Jawed** [comment]
Any update? Having the same issue
Android version: 6.0.1
RNCamera: 3.21.0

**Comment by PankajChaturvediDtechies** [comment]
having the same problem with ratio.

**Comment by YogiHa** [comment]
+1
