### ISSUE TITLE
 java.lang.NoSuchMethodError: No virtual method getCameraOrientation()I in class Lorg/reactnative/camera/RNCameraView; or its super classes

### ISSUE THREAD

**Issue by otaviogaiao** [react-native-camera/react-native-camera#2166]
# Bug Report
- [x] Did you try latest release?
- [x] Did you try master?
- [x] Did you look for existing matching issues?

**Related Modules**

RNCamera

**Platforms**

Android

**Versions**

- Android: SDK 23 e SDK 24
- iOS: iOS 12
- react-native-camera: 2.1.0
- react-native: 57.2 - ExpoKit 32
- react: 16.5.0
- react-navigation: 3.2.1

**Description/Current Behaviour**
If I open a camera with BarCodeScanner props, the app closes. On logcat I see the following error:

```
 java.lang.NoSuchMethodError: No virtual method getCameraOrientation()I in class Lorg/reactnative/camera/RNCameraView; or its super classes (declaration of 'org.reactnative.camera.RNCameraView' appears in /data/app/br.com.baladapp.produtor-1/split_lib_slice_4_apk.apk)
        at org.reactnative.camera.RNCameraView$1.onFramePreview(RNCameraView.java:125)
        at com.google.android.cameraview.CameraView$CallbackBridge.onFramePreview(CameraView.java:604)
        at com.google.android.cameraview.Camera1.onPreviewFrame(Camera1.java:766)
        at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1110)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
```

If I remove the onBarCodeRead and barCodeTypes, it works.

My code is:

```
      <RNCamera
        style={styles.container}
        type={RNCamera.Constants.Type.back}
        ref={this.cameraRef}
        captureAudio={false}
        onBarCodeRead={this.onCodeScanned}
        barCodeTypes={[RNCamera.Constants.BarCodeType.qr]}
      >
        <NavigationEvents onWillFocus={this.enableCam} onWillBlur={this.disableCam} />
        <TouchableOpacity style={styles.header} onPress={this.goBack} hitSlop={hitSlop15}>
          <MaterialCommunityIcons name="arrow-left" color={colors.branco} size={wp('7.4%')} />
          <Text style={styles.textVoltar}>Voltar</Text>
        </TouchableOpacity>
        {this.renderBody()}
      </RNCamera>

```

iOS works fine.
**Expected Behaviour**

The camera with barcodeProps should work.

**Steps to Reproduce**
Try to mount a camera with onBarCodeRead  and barCodeTypes

**Additionals**

![Screen Shot 2019-03-25 at 14 12 23](https://user-images.githubusercontent.com/3965485/54939789-3213c580-4f08-11e9-99b7-0e2df85370ea.png)
> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate
> Want this issue to be resolved faster? Please consider adding a bounty to it https://issuehunt.io/repos/33218414

**Comment by tugzera** [comment]
SAME ERROR HERE
