### ISSUE TITLE
Reading multiple barcodes at once on Android

### ISSUE THREAD

**Issue by iwashi1t** [react-native-camera/react-native-camera#2424]
# Feature-Request

**Describe the Feature**

Allow multiple barcodes to be read at once on Android (as with iOS).

Currently, for example, if there are three barcodes in the screen,  `onBarCodeRead` is called three times on iOS, but it seems to be called only once on Android.

**Possible Implementations**

How about using zxing's `GenericMultipleBarcodeReader.decodeMultiple` instead of `MultiFormatReader.decodeWithState`?

**Related Issues**

* #846
* #1593

**Comment by yrichard** [comment]
Oh man, I really wish this was fixed...

**Comment by yrichard** [comment]
Hi @MateusAndrade, any chance we can get that one re-opened? Or was there some specific limitations that prevent this from happen. Thank you :)

**Comment by MateusAndrade** [comment]
Hi @yrichard, we can re-open that and tag this as a feature request, btw maybe this would be a nice increment at v43. What do you think @MarcoScabbiolo ?

**Comment by MarcoScabbiolo** [comment]
I think scanning an entire frame for all the found barcodes and emitting all of them in a single event is something we can get done.

In v4 the scanning stops as soon as event is fired, and the event comes with a callback to resume the scanning. That's at least a starting point, and should prevent the du/triplicated events in iOS.

I agree this should go to v4.

**Comment by yrichard** [comment]
Is it me or you guys are rocking hard?
