### ISSUE TITLE
takePicture failed - Android

### ISSUE THREAD

**Issue by lucasferreiraestevam** [react-native-camera/react-native-camera#2665]
Android : 9
react-native-camera : v3.15.1
react-native : 0.61.5

Possible Unhandled Promise Rejection (id: 1) : Error: takePicture failed...

https://codepen.io/lucasferreiraestevam/pen/MWYrQBj.js

![Captura de Tela 2020-01-06 às 11 47 25](https://user-images.githubusercontent.com/12140708/71825361-77aa1500-307a-11ea-8de9-ae454599b211.png)

**Comment by lucasferreiraestevam** [comment]
Solved !

____________

Only on android if setState is called before the takePictureAsync function sometimes RNcamera returns Possible Unhandled Promise Rejection (id: 1): Error: takePicture failed ...

**Comment by pereirafabiosantos2018** [comment]
This is happening to me on Android device.

**Comment by pereirafabiosantos2018** [comment]
When I try press the button to open camera, the following error occurs:
error Error: takePicture failed
    at Object.fn [as takePicture]

**Comment by NguyenHuuManh** [comment]
i have same problem, please help me!

**Comment by leonidlewis** [comment]
Same here!

**Comment by CalmNguyen** [comment]
Same!
