### ISSUE TITLE
mirrorVideo not work on Android

### ISSUE THREAD

**Issue by kperreau** [react-native-camera/react-native-camera#2811]
# Bug Report

**To Do First**

- [x] Did you try latest release?
- [x] Did you try master?
- [x] Did you look for existing matching issues?

**Platforms**
Android

**Versions**

- Android: 9
- react-native-camera: 3.23.1
- react-native: 0.62.2
- react: 16.11.0
- react-navigation: 4.3.8

**Description/Current Behaviour**

Option `mirrorVideo` from `recordAsync()` not work on Android (recording video).

**Expected Behaviour**

Video should be mirrored.

**Steps to Reproduce**

Record a video on Android device with option `mirrorVideo` set to `true`.

**Comment by fabriziobertoglio1987** [comment]
search before posting issue https://github.com/react-native-community/react-native-camera/issues/2594#issuecomment-555044291

**Comment by joseym90** [comment]
I have the same issue,

Android: 10
react-native-camera: 3.30.0
react-native: 0.61.4
react: 16.9.0
react-navigation: 4.0.10

The mirrorVideo option doesn't make any effect on the recorded video. With the back-facing camera, video is normally recorded (as same as you see during the process). With the front camera, the recorded video is mirrored respecting the recorded image.

**Comment by unandreshevia** [comment]
I'm having the exact same issue here.

Android: 9
react-native-camera: 3.30.0
react-native: 0.59.5
