### ISSUE TITLE
playSoundOnCapture implementation for iOS

### ISSUE THREAD

**Issue by airowe** [react-native-camera/react-native-camera#2860]
# Question

**To Do First**
- [x] Take a look in the [README](https://github.com/react-native-community/react-native-camera/blob/master/README.md)
- [x] Take a look in the [docs](https://github.com/react-native-community/react-native-camera/blob/master/docs/RNCamera.md)
- [x] Take a look in the [QA](https://github.com/react-native-community/react-native-camera/blob/master/docs/QA.md)

**Ask your Question**
Is there a `playSoundOnCapture` implementation for iOS?

**Tags**
ios sound

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate
> Want this issue to be resolved faster? Please consider adding a bounty to it https://issuehunt.io/repos/33218414

**Comment by 0xori** [comment]
is it possible?

**Comment by 0xori** [comment]
still happening
