### ISSUE TITLE
focusDepth doesn't work on Android

### ISSUE THREAD

**Issue by ferbeab** [react-native-camera/react-native-camera#2932]
# Bug Report

**To Do First**

- [x] Did you try latest release?
- [x] Did you try master?
- [x] Did you look for existing matching issues?

**Platforms**

**Versions**

- Android: 9 & 10
- react-native-camera: 3.35.0
- react-native: 0.63.2
- react: 16.13.1
  

**Description/Current Behaviour**

Setting autoFocus off freezes camera focus at current depth. However, passing a value to focusDepth doesn't modify camera focus.

**Expected Behaviour**

When autoFocus is off, camera focus should match the value passed to focusDepth prop

**Steps to Reproduce**

A test repo to reproduce this error can be found here: https://github.com/ferbeab/testLab
Just pass different values between 0 - 1 to focusDepth and check if camera focus changes

**Additionals**

> Love react-native-camera? Please consider supporting our collective: 👉 https://opencollective.com/react-native-camera/donate
> Want this issue to be resolved faster? Please consider adding a bounty to it https://issuehunt.io/repos/33218414

**Comment by vetrivendhan48** [comment]
This ticket has more information about this issue - #2985 .
