### ISSUE TITLE
Haptic Feedback doesn't work if `captureAudio` enabled

### ISSUE THREAD

**Issue by Jonovono** [react-native-camera/react-native-camera#2934]
Has anyone faced this? I am using the react native haptic feedback library. If I have the `captureAudio` prop on then haptic doesn't work, but if disabled its fine. I'm guessing it interferes but anyone know of a solution?

**Comment by cristianoccazinsp** [comment]
Is it vibration that doesn't work?  I think I saw this once.  iOS treats vibration just like sound, so trying to play a vibration pattern while "sound is on" (i.e., `captureAudio=true`) will not work.  Your only option is to set it to `false` and only turn it on if you are in fact trying to record with sound.

**Comment by nhannah** [comment]
> captureAudio=true

There are multiple threads about the limitation of haptic on iOS when the camera is in use. Haptic doesn't fire for a variety of reasons on iOS, low battery being another example, this is not a React Native issue but intended behavior on iOS.
