### ISSUE TITLE
rectOfInterest is not supported on onGoogleVisionBarcodesDetected with ML Kit

### ISSUE THREAD

**Issue by hamarles12** [react-native-camera/react-native-camera#2937]
# Bug Report

**To Do First**

- [x ] Did you try latest release?
- [x ] Did you try master?
- [x] Did you look for existing matching issues?

**Platforms**

Android

**Versions**

"react": "16.11.0",
"react-native": "0.62.2",
"react-native-camera": "^3.26.0"
"react-native-barcode-mask": "^1.2.2",

**Description/Current Behaviour**

As soon as a barcode enters the camera field, onGoogleVisionBarcodesDetected pick it up even if the barcode is on the outside of the finder area.

rectOfInterest works on onBarCodeRead but not on onGoogleVisionBarcodesDetected with ML Kit

**Expected Behaviour**

rectOfInterest should work on onGoogleVisionBarcodesDetected with ML Kit

**Comment by GiannCarlo** [comment]
+1 .  Any solutions ?

**Comment by LoverFancy** [comment]
same issues how to limit the face detection erea in react-native-camera

**Comment by amirulasrof** [comment]
Same issue, rectOfInterest work fine onBarcodeRead but not onGoogleVisionBarcodesDetected.
