### ISSUE TITLE
Promise returned by takePictureAsync doesn't resolve Android SDK 30

### ISSUE THREAD

**Issue by VadimDyliko** [react-native-camera/react-native-camera#2953]
# Bug Report

**To Do First**

- [x] Did you try latest release?
- [x] Did you try master?
- [x] Did you look for existing matching issues?

**Platforms**

Android

**Versions**

- Android: 10+ SDK 30.0.2
- react-native-camera: 3.36.0
- react-native: 0.62.2
- react: 16.13.1

**Description/Current Behaviour**

**SDK 30.0.2**
Promise returned by takePictureAsync doesn't resolve while using main camera. 
If try to use front camera it works well.

**SDK 28.0.3**
Works well.

**Expected Behaviour**

Promise returned by takePictureAsync resolves with picture data.

**Comment by hansa0712004212** [comment]
I'm having same issue. Tested on Android 10 (GooglePlay) emulator, Xiaomi Mi A3 Android 10, Redmi Note 8 Pro Android 10 MIUI 12.
Permissions given.
    <uses-permission android:name="android.permission.ACCESS_MEDIA_LOCATION" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

Software versions.
    "react": "16.13.1",
    "react-native": "0.63.2",
    "react-native-camera": "^3.37.0",

**Comment by cristianoccazinsp** [comment]
Leaving a comment to see how this evolves since Android 11 is just around the corner and this SDK will eventually be the required one.

Have you tried SDK 29?  You mention it works with 28 and it doesn't with 30, I wonder if it works with 29.

**Comment by VadimDyliko** [comment]
> Have you tried SDK 29? You mention it works with 28 and it doesn't with 30, I wonder if it works with 29.

Yep, it works well with sdk 29.

**Comment by betocode** [comment]
happens with me on SDK 28.0.3, front camera works well but main camera doesnt

**Comment by timothytjp** [comment]
Experiencing the same issue on API v30. Discovered a workaround, if you change the camera on the AVD to use Emulated instead of VirtualScene or Webcam, I was able to get it to resolve.
