### ISSUE TITLE
Camera handle cannot be null error

### ISSUE THREAD

**Issue by jenipharachel** [react-native-camera/react-native-camera#2956]
The react-native-camera is working and a white space is shown in the place of the camera view in Samsung note 10 phone with the alert "**Camera handle cannot be null**" since there's no feed from the camera. The issue is only in this particular device

**Comment by Ulkeshwani** [comment]
Same Alert On My side also and Also the Activity Indicator is showing. i am using redmi note 8 .
here is my code:-

 <View style={styles.container}>
        <RNCamera
          ref={(ref) => {
            this.camera = ref;
          }}
          style={styles.preview}
          type={RNCamera.Constants.Type.back}
          flashMode={RNCamera.Constants.FlashMode.off}
          captureAudio={true}
          // androidCameraPermissionOptions={{
          //   title: "Permission to use camera",
          //   message: "We need your permission to use your camera",
          //   buttonPositive: "Ok",
          //   buttonNegative: "Cancel",
          // }}
        />
        <View
          style={{ flex: 0, flexDirection: "row", justifyContent: "center" }}
        >
          <TouchableOpacity
            onPress={this.takePicture.bind(this)}
            style={styles.capture}
          >
            <Text style={{ fontSize: 14 }}> SNAP </Text>
          </TouchableOpacity>
        </View>
      </View>

please respond if any mistakes i have done.

**Comment by VBSwebs** [comment]
Same error Occur in my Hot 9 Play Infinix  Android Phone .When i am redirect on Camera screen then just show a black screen and when i am clicking on Snap button then this error occur "Camera handle cannot be null"    .

here is my code 👍 
 render() {
    return (
      <View style={styles.container}>
        <RNCamera
          ref={(ref) => {
            this.camera = ref;
          }}
          style={styles.preview}
          type={RNCamera.Constants.Type.back}
          flashMode={RNCamera.Constants.FlashMode.on}
          androidCameraPermissionOptions={{
            title: 'Permission to use camera',
            message: 'We need your permission to use your camera',
            buttonPositive: 'Ok',
            buttonNegative: 'Cancel',
          }}
          androidRecordAudioPermissionOptions={{
            title: 'Permission to use audio recording',
            message: 'We need your permission to use your audio',
            buttonPositive: 'Ok',
            buttonNegative: 'Cancel',
          }}
          onGoogleVisionBarcodesDetected={({ barcodes }) => {
            console.log(barcodes);
          }}
        />

        <View
          style={{
            flex: 0,
            flexDirection: 'row',
            // width: '50%',
            justifyContent: 'center',
            backgroundColor: 'transparent',
          }}>
          <TouchableOpacity
            onPress={this.takePicture.bind(this)}
            style={styles.capture}>
            <Text style={{ fontSize: 14 }}> SNAP </Text>
          </TouchableOpacity>
        </View>
      </View>
    );
  }

  takePicture = async () => {
    if (this.camera) {
      const options = { quality: 0.5, base64: true };
      const data = await this.camera.takePictureAsync(options);
      console.log(data.uri);
    }
  };
}

**Comment by TayyabaAslam3317** [comment]
I am facing exact same issue and for me at this point  await this.camera.takePictureAsync(options); this.camera does not have any handle. This happens on and off not everytime.
