### ISSUE TITLE
 Face bounding box is consistently off for android devices

### ISSUE THREAD

**Issue by sbycrosz** [react-native-camera/react-native-camera#2966]
# Bug Report

**To Do First**

- [x] Did you try latest release?
- [x] Did you try master?
- [x] Did you look for existing matching issues?

**Platforms**

Android

**Versions**

- Android: Android 10
- iOS: N/A
- react-native-camera: 3.36.0
- react-native: 61.5
- react:16.9.0

**Description/Current Behaviour**

![image](https://user-images.githubusercontent.com/4867178/92378712-d4455e80-f138-11ea-907c-27d65c617f53.png)

Face bounding box is consistently off for android devices

Meanwhile, iOS is working as expected.

**Expected Behaviour**

Face bounding box should bound faces 

**Steps to Reproduce**

```
<View style={[s.absolute_fill]}>
  <RNCamera
    ref={camera}
    type='front'

    autoFocus={RNCamera.Constants.AutoFocus.on}
    captureAudio={false}

    androidCameraPermissionOptions={{
      title: t('self-portrait.viewfinder.android-permission-dialog.title'),
      message: t('self-portrait.viewfinder.android-permission-dialog.message'),
      buttonPositive: t('self-portrait.viewfinder.android-permission-dialog.button-positive'),
      buttonNegative: t('self-portrait.viewfinder.android-permission-dialog.button-negative'),
    }}

    onFacesDetected={onFacesDetected}

    style={[s.absolute_fill]} />
    
  {renderFaces()}
</View>
```

**Comment by cristianoccazinsp** [comment]
Does it work with landscape?

**Comment by sbycrosz** [comment]
Hi, 

We found out that setting a ratio on RNCamera will fix the bounding box issues.

Then, we try using getSupportedRatiosAsync to find the best match ratio given device resolution. 
But we found that changing the ratio prop when RNCamera is mounted will somehow stretch the preview image horizontally

I think we are close.

Cheers,

**Comment by sbycrosz** [comment]
Hi, 

With further testing, we found that:

1. On landscape, faces seem to be rotated by 90 degrees
2. Setting up the ratio prop before RNCamera is rendered would fix this issue (faces detected correctly)
3. We can't do (2) because getSupportedRatioAsync can only be called after RNCamera is rendered
4. Changing the ratio prop after RNCamera is rendered would cause the preview image to be stretched horizontally

Cheers, 
Sam

(1)
<img src="https://user-images.githubusercontent.com/4867178/92450225-bbe34b80-f1ed-11ea-98bc-18108a2c6657.png" alt="drawing" width="400"/>

(4)
<img src="https://user-images.githubusercontent.com/4867178/92450239-c1409600-f1ed-11ea-9d75-177938af60a2.png" alt="drawing" width="250"/>

**Comment by cristianoccazinsp** [comment]
Were you trying 4:3 and 16:9 ratios? I think you may have an issue with the camera taking the whole screen (which is technically incorrect, look at the native camera). 

For example, if you are using 4:3, you should build your view dimensions so it fits into a 4:3 rectangle. The following picture shows a 4:3 view that takes as much height/width (based on on portrait or landscape) as possible while leaving the other one adjust automatically.

![image](https://user-images.githubusercontent.com/48869228/92482226-c1c13880-f1bd-11ea-9e8e-be0a4fb795ea.png)

So if you are using 4:3, you will need the black lines on the sides (I think). If you are using 16:9, then you may be able to take the full dumensions of the screen on some devices.

**Comment by sbycrosz** [comment]
![image](https://user-images.githubusercontent.com/4867178/92551534-d3274500-f290-11ea-9bc0-7348b89c41c8.png)

Interesting. so I guess we could probably set the RNCamera ratio to 4:3 & render it slightly bigger than the screen for a workaround 

And even more interesting, we found this [aspect prop](https://github.com/react-native-community/react-native-camera/blob/master/android/src/main/java/com/lwansbrough/RCTCamera/RCTCameraView.java#L195) that seems to do that (but we haven't manage to get it working yet)
