### ISSUE TITLE
PDF417 Barcode Scanning with Front-Facing Camera on iPad

### ISSUE THREAD

**Issue by pjwl33** [react-native-camera/react-native-camera#2973]
# Question

Hello RNCamera Team,

Was wondering if PDF417 Barcode Scanning is possible with an iPad 2's front-facing camera. 

I am able to scan a PDF417 barcode using the same exact code but just switching to rear camera (`RNCamera.Constants.Type.front vs RNCamera.Constants.Type.back`). 

Unable to scan on front camera regardless of rotating the barcode around in ever angle.

Environment specs:
```
iPad 2, iOS v.13.7
react-native: 0.63.2
```

**To Do First**
- [x] Take a look in the [README](https://github.com/react-native-community/react-native-camera/blob/master/README.md)
- [x] Take a look in the [docs](https://github.com/react-native-community/react-native-camera/blob/master/docs/RNCamera.md)
- [x] Take a look in the [QA](https://github.com/react-native-community/react-native-camera/blob/master/docs/QA.md)

**Ask your Question**

**Tags**

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate
> Want this issue to be resolved faster? Please consider adding a bounty to it https://issuehunt.io/repos/33218414

**Comment by aniruddhbhamare** [comment]
hey , can you plz share the steps and code which is working on iOS (rear camera ) , on my case it works fine on android device (PDF 417) . but on iOS it crashes the app . thanks in advance !
