### ISSUE TITLE
Error when pod install FirebaseML kit

### ISSUE THREAD

**Issue by Nadreasky** [react-native-camera/react-native-camera#2974]
I have followed instruction guide when install react-native-camera library for my project. Because I want to use Barcode and Text Recognition so I have modified my Podfile by adding below code

`pod 'react-native-camera', path: '../node_modules/react-native-camera', subspecs: [
  'TextDetector',
  'BarcodeDetectorMLKit'
  ]`

but when run command `pod install`, I got a warning like:

[!] FirebaseMLVisionBarcodeModel has been deprecated in favor of MLKitBarcodeScanning

[!] FirebaseMLVisionTextModel has been deprecated in favor of MLKitTextRecognition

Not sure my app is still working or not (because I'm still writing code for now), but I think sooner or later I need to update those deprecated pod.

Please help me to check and give me advices for this case. Thank you very much!

**Comment by BooYeu** [comment]
I have same problem

**Comment by ramezyouakimf** [comment]
I have the same problem

**Comment by sarojswain680** [comment]
I have the same problem

**Comment by Donhv** [comment]
Does anyone maintain this repo?

**Comment by GiannCarlo** [comment]
still an issue

**Comment by faizantariq1** [comment]
still got the warning. [!] FirebaseMLVisionTextModel has been deprecated in favor of MLKitTextRecognition. when will you guys convert it into MLKitTextRecognition?

**Comment by KPS250** [comment]
Still facing the same issue. QRCode Scanning is working for Android but not for iOS. Any update  on this?

**Comment by notjulian** [comment]
Hi
I've patched the latest version this way:

```
diff --git a/node_modules/react-native-camera/react-native-camera.podspec b/node_modules/react-native-camera/react-native-camera.podspec
index a67d1fd..3df9191 100644
--- a/node_modules/react-native-camera/react-native-camera.podspec
+++ b/node_modules/react-native-camera/react-native-camera.podspec
@@ -26,22 +26,19 @@ Pod::Spec.new do |s|
   s.subspec "TextDetector" do |ss|
     ss.dependency 'react-native-camera/RN'
     ss.dependency 'react-native-camera/RCT'
-    ss.dependency 'Firebase/MLVision'
-    ss.dependency 'Firebase/MLVisionTextModel'
+    ss.dependency 'GoogleMLKit/BarcodeScanning'
   end
 
   s.subspec "FaceDetectorMLKit" do |ss|
     ss.dependency 'react-native-camera/RN'
     ss.dependency 'react-native-camera/RCT'
-    ss.dependency 'Firebase/MLVision'
-    ss.dependency 'Firebase/MLVisionFaceModel'
+    ss.dependency 'GoogleMLKit/BarcodeScanning'
   end
 
   s.subspec "BarcodeDetectorMLKit" do |ss|
     ss.dependency 'react-native-camera/RN'
     ss.dependency 'react-native-camera/RCT'
-    ss.dependency 'Firebase/MLVision'
-    ss.dependency 'Firebase/MLVisionBarcodeModel'
+    ss.dependency 'GoogleMLKit/BarcodeScanning'
   end
 
   s.default_subspecs = "RN", "RCT"
```

```
"react-native": "0.64.2"
"react-native-camera": "^3.43.9"
```

**Comment by KPS250** [comment]
@notjulian thanks for the quick help. I was able to successfully install the pods and run the project but however its not detecting QRCodes/BarCodes  on iOS.

**Comment by notjulian** [comment]
> @notjulian thanks for the quick help. I was able to successfully install the pods and run the project but however its not detecting QRCodes/BarCodes on iOS.

are you using this method?

`onBarCodeRead={this.onBarCodeRead}`

**Comment by wojteg1337** [comment]
@notjulian you should specify bar code types

**Comment by KPS250** [comment]
> > @notjulian thanks for the quick help. I was able to successfully install the pods and run the project but however its not detecting QRCodes/BarCodes on iOS.
> 
> I'm using this code ... ( please check `onBarCodeRead`)
> 
> ```
> <RNCamera
>       style={styles.preview}
>       type={RNCamera.Constants.Type.back}
>       captureAudio={false}
>       //flashMode={RNCamera.Constants.FlashMode.on}
>       onBarCodeRead={this.onBarCodeRead}></RNCamera>
> ```

This worked!

**Comment by mahecode** [comment]
onTextRecognized but this is not working any help here ?
