### ISSUE TITLE
incorrect scanned code

### ISSUE THREAD

**Issue by gersualves775** [react-native-camera/react-native-camera#2978]
# Bug Report

- [ X] Did you try latest release?
- [ X] Did you try master?
- [ X] Did you look for existing matching issues?

- Android:
- iOS:
- react-native-camera: 3.29.1 / 3.23.1
- react-native: 0.62.1
- react: 16.11.0

![image](https://user-images.githubusercontent.com/56324804/93516713-cf369b00-f900-11ea-826e-d790bcaf7ccb.png)

Hello, my problem is with barcode reading.
This for example, your code is
23793 38128 60039 508019 87000 063302 1 83820000002000

But the react-native-camera insists on returning me another code.

**Comment by gersualves775** [comment]
up

**Comment by Ashafix** [comment]
Strange, I tried two other programs (Android app: QR & Barcode Scanner and https://online-barcode-reader.inliteresearch.com/). Both return the same text: 00192832500000096430000003197150014510642017.

Is it possible that the software which generated the barcode misinterpreted your input?

**Comment by MateusAndrade** [comment]
This is Brazillian Boleto @gersualves775 ?

**Comment by gersualves775** [comment]
Yes @MateusAndrade.
The problem is that I always used it and it worked. After updating some features, the problem occurs.

**Comment by gersualves775** [comment]
@Ashafix 
me too.
But the RNCamera return  23793 38128 60039 508019 87000 063302 1 83820000002000

**Comment by Ashafix** [comment]
@gersualves775 
I tried with RNCamera 3.36 and React Native 0.62. The code was correctly recognized in an emulated device.
