### ISSUE TITLE
Is there a fork/feature of *this library* that can do text detection on image picker/gallery images?

### ISSUE THREAD

**Issue by trackwell-mike** [react-native-camera/react-native-camera#2988]
I'm curious if there is a fork or feature branch of **react-native-camera** that allows the text detection capabilities to be applied to the image picker/gallery.

We are currently using [react-native-text-detector](https://github.com/zsajjad/react-native-text-detector) but it's no longer maintained and not as accurate as react-native-camera.

**Comment by doranteseduardo** [comment]
There is not, but you can use [RNF ML Vision](https://rnfirebase.io/ml-vision/text-recognition) to achieve that goal.
RNCamera uses the same.
