### ISSUE TITLE
Why doesn't work onTap and useNativeZoom in RNCamera?

### ISSUE THREAD

**Issue by ombogdan** [react-native-camera/react-native-camera#2990]
I used onTap event : onTap={this._myFunction}. But it doesn't work
I used useNativeZoom like that: useNativeZoom ={true}. But it doesn't work

**Comment by SimonErm** [comment]
Please use the Issue Template for better support.
Do you have view filling nested views? 

> Warning: The Android Touch-Event-System causes childviews to catch the touch events. Therefore avoid using screenfilling touchables inside of the cameraview.
(https://react-native-camera.github.io/react-native-camera/docs/rncamera#usenativezoom)
