### ISSUE TITLE
Stretched video when recording in portrait mode (ios)

### ISSUE THREAD

**Issue by yesterday24** [react-native-camera/react-native-camera#2994]
I have a problem on IOS 14.0, RN version 0.63.2.

When using RNCamera and recording a video in **portrait mode**, the resulting video is stretched. When recording in **landscape mode**, everything works fine.

I've included some screenshots from my device.

![IMG_0461](https://user-images.githubusercontent.com/58610521/95361714-602fdf00-08cd-11eb-8d28-77fe8ec13da8.PNG)

Screenshot 1: video recorded in portrait mode. The video (as seen in the screenshot above) is stretched horizontally, while it should be more of a rectangle (height > width), so stretched vertically, not horizontally.

![IMG_0462](https://user-images.githubusercontent.com/58610521/95361805-7b025380-08cd-11eb-8391-6370c668357a.PNG)

Screenshot 2: this video is recorded in landscape mode. The video is not stetched but is rotated 90°.

How can I fix these issues, or is this a bug? It's weird, because it worked before.

**Comment by Cristi6** [comment]
Having the same issue, looking forward for a fix or at least a quick solution

**Comment by wxsms** [comment]
I have meet the same issue, but only with some ios devices, not all of them.

**Comment by wxsms** [comment]
maybe duplicated with #2979
