### ISSUE TITLE
Problem saving photo, with a filter on the face

### ISSUE THREAD

**Issue by fera765** [react-native-camera/react-native-camera#2997]
I mounting a lib to detect a face and add filters, but when saving the image the filter is disappearing ....

As an alternative I tried to use the react-native-view-shot but I got the same problem, I realized that when I used the camera it excels over the other components

**Comment by doranteseduardo** [comment]
Which library are you using?
If the filters are an overlap then they're never going to be part of the captured picture.

**Comment by fera765** [comment]
> Which library are you using?
> If the filters are an overlap then they're never going to be part of the captured picture.


I'm using react-native-view-shot, to try to capture the photo ...

However, in all the methods available for this lib I was not successful...
I have the same problem in this link below where a developer faced the same problems

https://github.com/react-native-camera/react-native-camera/issues/2035

**Comment by doranteseduardo** [comment]
I meant the filters library.
I've checked the view-shot library, it has an interoperability table on its README, it seems to work well with react-native-camera on Android but not on iOS.

**Comment by fera765** [comment]
> I meant the filters library.
> I've checked the view-shot library, it has an interoperability table on its README, it seems to work well with react-native-camera on Android but not on iOS.



I'm assembling the effects by hand, without using third libraries ....

But even when I try to capture the photo with a simple <Text>, it doesn't work either.
These two photos also show some Views, which does not appear when capturing the photo ...
Try using position absolute, and relative, zindex and nothing caught,
I even looked for some other lib of camera with facial recognition, but I didn't find anything nice ...

![photo4909283418060204181 (1)](https://user-images.githubusercontent.com/35400150/96296901-68230980-0fc6-11eb-8d6d-a1f074ff9286.jpg)
![photo4909283418060204182 (1)](https://user-images.githubusercontent.com/35400150/96296905-69eccd00-0fc6-11eb-8bde-4566f1ac9e89.jpg)

**Comment by doranteseduardo** [comment]
Well, that's unfortunate, but in terms of react-native-camera, it won't get your filters rendered on the saved picture because they are not part of the picture.

Using react-native-view-shot seems to be the most feasible option for now, but as it doesn't work well capturing the camera view on iOS, you could try the following approach:

- Take your photo using react-native-camera.
- After your photo is captured, show the picture in the fullscreen.
- Put your filters above the picture.
- Use react-native-view-shot to capture that view.

Tried it on Android 10 and worked well.

**Comment by fera765** [comment]
> Well, that's unfortunate, but in terms of react-native-camera, it won't get your filters rendered on the saved picture because they are not part of the picture.
> 
> Using react-native-view-shot seems to be the most feasible option for now, but as it doesn't work well capturing the camera view on iOS, you could try the following approach:
> 
> - Take your photo using react-native-camera.
> - After your photo is captured, show the picture in the fullscreen.
> - Put your filters above the picture.
> - Use react-native-view-shot to capture that view.
> 
> Tried it on Android 10 and worked well.
> 
> 

I also thought about this possibility to capture the image, and then use a new library to identify the user's face and then apply the filter ...... But I thought it would be a little strange for my purpose 🤪

I had found react native opencv 3, however it only works in landscaoe mode and I didn't like it very much

**Comment by fera765** [comment]
react-native-opencv3 is a nice lib, but it has some problems and is no longer maintained by the project owner

**Comment by vannguyendev96** [comment]
did you fix this error? @fera765

**Comment by wiredmatrix** [comment]
Any solution for this issue?
My filters are not saving after recording a video with RNCamera.
