### ISSUE TITLE
onDoubleTap event not working on Android

### ISSUE THREAD

**Issue by umang-simform** [react-native-camera/react-native-camera#2999]
# Bug Report

**To Do First**

- [*] Did you try latest release?
- [ ] Did you try master?
- [*] Did you look for existing matching issues?

**Platforms**

Happening on Android only

**Versions**

- Android: Any
- iOS:NA
- react-native-camera:"^3.40.0"
- react-native: "0.63.3"
- react: "16.13.1"
- react-navigation: 4.4.1

**Description/Current Behaviour**
`onDoubleTap` event not working on android while it is working fine on iOS

Add function like this and it will crash when user actually performs double tap
onDoubleTap={() => {
              console.log('on double tap called');
            }}
**Expected Behaviour**
It should not crash the application and the console should log the above mentioned text

It should print : on double tap called
**Steps to Reproduce**
Add function as mentioned above then run the app on any android device/emulator, when you will perform this action app will be crashed

Same as above

**Additionals**

![Screenshot_1602680344](https://user-images.githubusercontent.com/61829970/95993035-3c7c1400-0e4c-11eb-8ba7-8b399cb7ae4f.png)

> Love react-native-camera? Please consider supporting our collective: 👉 https://opencollective.com/react-native-camera/donate
> Want this issue to be resolved faster? Please consider adding a bounty to it https://issuehunt.io/repos/33218414

**Comment by SimonErm** [comment]
Fixed in #3009
