### ISSUE TITLE
Camera not authorized in windows

### ISSUE THREAD

**Issue by Shing-Ho** [react-native-camera/react-native-camera#3003]
# Bug Report

**To Do First**

- [ Y] Did you try latest release?
- [ Y] Did you try master?
- [ Y] Did you look for existing matching issues?

**Platforms**
Windows

**Versions**
0.63.2

- Android:
- iOS:
- react-native-camera: 3.40
- react-native: 0.63.2
- react: 16.13.1
  

**Description/Current Behaviour**
I am having Camera not Authorized in the screen

```
<RNCamera
        style={styles.preview}
        type={RNCamera.Constants.Type.back}
        onGoogleVisionBarcodesDetected={({ barcodes }) => {
          console.log(barcodes);
        }}
      />
```
![image](https://user-images.githubusercontent.com/57267692/96373714-20fe5b00-1123-11eb-9bc5-57abd8e7193e.png)

Also, I've added permission in the capabilities of webcam.

**Comment by anirudh-jwala** [comment]
Under `android->app->build.gradle` add the following lines

```
defaultConfig {
   ....
   missingDimensionStrategy 'react-native-camera', 'general'
}
```
