### ISSUE TITLE
Documentation link 404

### ISSUE THREAD

**Issue by dbasilioesp** [react-native-camera/react-native-camera#3004]
# Bug Report

When I click in link for documentation from README, I get a page with 404.

![image](https://user-images.githubusercontent.com/894329/96460054-33e35f00-11f9-11eb-942e-30caf8939ef8.png)

**Comment by AutomaticWaffle** [comment]
Docs were moved to here: https://react-native-camera.github.io/react-native-camera/

**Comment by felippepuhle** [comment]
Fixed on https://github.com/react-native-camera/react-native-camera/pull/3005
