### ISSUE TITLE
Does the library only not support USB external cameras or all external cameras? (including Bluetooth external connection)

### ISSUE THREAD

**Issue by Shuo-Mr** [react-native-camera/react-native-camera#3006]
# Question

--I learned that getcameraidsasync in the document can get the camera ID. can I get the external camera ID?
It is mentioned in # 802 that the library does not support cameras with USB interface. Well, I have a requirement now that I really need external cameras. The library cannot support USB. What about Bluetooth and other external cameras? Are they not supported?

- As for Bluetooth camera, I have not actually tested it, because there is no actual hardware, so if it can be supported, then it is the best.

- Or can you give me a little help and how to deal with this situation? I have checked some projects and libraries, some of which are pure java development, and can link to external cameras (USB), but for those who are not involved in Java, it is really difficult.

Thank!

**Comment by AndriiDidkivsky** [comment]
@Shuo-Mr did you find information about that ? 
I've trapped in the same issue.
