### ISSUE TITLE
Use of undeclared identifier 'FIRApp' in iOS when using TextRecognition 

### ISSUE THREAD

**Issue by tmoorthymca** [react-native-camera/react-native-camera#3008]
I have tried to using below react-native-camera for **TextRecognition** in iOS.

***react-native-camera-3.40.0***

Its working when  creating dev build. but its not working for Archive(Release Build). In Android its working fine. In iOS I got below error message.

**"Use of undeclared identifier 'FIRApp'"**  in **AppDelegation.m** @[FIRApp configure];

I updated Cocoa-pods and **Firebase(6.34.0)** lates version but still the issue is present. Please help us resolve the issue.

**Comment by GBabaBatyr** [comment]
Same here

**Comment by sahinbezeng** [comment]
In AppDelegate.m file, you should import firebase like `#import <Firebase.h>` before `#ifdef FB_SONARKIT_ENABLED` line.

As I understand, You probably get success on dev build because FlipperKit libraries are used for debugging and this `#ifdef FB_SONARKIT_ENABLED` if condition is satisfied. When you try to archive it will not be imported and the variables will be undeclared because `#import <Firebase.h>` remains in that if condition.

I got the same problem and it was solved in this way.

**Comment by jyu520** [comment]
> In AppDelegate.m file, you should import firebase like `#import <Firebase.h>` before `#ifdef FB_SONARKIT_ENABLED` line.
> 
> As I understand, You probably get success on dev build because FlipperKit libraries are used for debugging and this `#ifdef FB_SONARKIT_ENABLED` if condition is satisfied. When you try to archive it will not be imported and the variables will be undeclared because `#import <Firebase.h>` remains in that if condition.
> 
> I got the same problem and it was solved in this way.

Someone needs to add this to the docs!

**Comment by chrismazzeo** [comment]
totally agree, happen the same to me, thanks for the answer @jyu520

**Comment by sakthiinfotec** [comment]
> > In AppDelegate.m file, you should import firebase like `#import <Firebase.h>` before `#ifdef FB_SONARKIT_ENABLED` line.
> > As I understand, You probably get success on dev build because FlipperKit libraries are used for debugging and this `#ifdef FB_SONARKIT_ENABLED` if condition is satisfied. When you try to archive it will not be imported and the variables will be undeclared because `#import <Firebase.h>` remains in that if condition.
> > I got the same problem and it was solved in this way.
> 
> Someone needs to add this to the docs!

Thanks @jyu520! The solution worked for me

**Comment by aymkin** [comment]
Also, helpful use condition, ad mentioned [here](https://rnfirebase.io/#configure-firebase-with-ios-credentials)

```swift
if ([FIRApp defaultApp] == nil) {
      [FIRApp configure];
    }
```

**Comment by pardeshishubham** [comment]
What work for me,
Just add
 `#import <Firebase.h>` to the AppDelegate.h as well

**Comment by aliraza96** [comment]
> What work for me,
> Just add
> `#import <Firebase.h>` to the AppDelegate.h as well

Perfect Solution. Worked for me. Thanks

**Comment by surajprasad13** [comment]
> What work for me, Just add `#import <Firebase.h>` to the AppDelegate.h as well

Thanks for saving my time

**Comment by sarimahmad** [comment]
> 

You are my Loveee ❤️❤️❤️❤️❤️

**Comment by sarimahmad** [comment]
> What work for me,
> Just add
> `#import <Firebase.h>` to the AppDelegate.h as well

Loveee you bro Saved my time ❤️

**Comment by criticalmiind** [comment]
ISSUE: undeclared identifier 'FIRApp' in iOS 


Solution:
AppDelegate.m


`
#import "AppDelegate.h"

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>

// Add Line Must Before #ifdef FB_SONARKIT_ENABLED
#import <Firebase.h>

#ifdef FB_SONARKIT_ENABLED
#import <FlipperKit/FlipperClient.h>
#import <FlipperKitLayoutPlugin/FlipperKitLayoutPlugin.h>
#import <FlipperKitUserDefaultsPlugin/FKUserDefaultsPlugin.h>
#import <FlipperKitNetworkPlugin/FlipperKitNetworkPlugin.h>
#import <SKIOSNetworkPlugin/SKIOSNetworkAdapter.h>
#import <FlipperKitReactPlugin/FlipperKitReactPlugin.h>

static void InitializeFlipper(UIApplication *application) {
  FlipperClient *client = [FlipperClient sharedClient];
  SKDescriptorMapper *layoutDescriptorMapper = [[SKDescriptorMapper alloc] initWithDefaults];
  [client addPlugin:[[FlipperKitLayoutPlugin alloc] initWithRootNode:application withDescriptorMapper:layoutDescriptorMapper]];
  [client addPlugin:[[FKUserDefaultsPlugin alloc] initWithSuiteName:nil]];
  [client addPlugin:[FlipperKitReactPlugin new]];
  [client addPlugin:[[FlipperKitNetworkPlugin alloc] initWithNetworkAdapter:[SKIOSNetworkAdapter new]]];
  [client start];
}
#endif

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{

// Add This Condition
if ([FIRApp defaultApp] == nil) {
  [FIRApp configure];
}
// End

#ifdef FB_SONARKIT_ENABLED
  InitializeFlipper(application);
#endif

  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"Rider"
                                            initialProperties:nil];

  if (@available(iOS 13.0, *)) {
      rootView.backgroundColor = [UIColor systemBackgroundColor];
  } else {
      rootView.backgroundColor = [UIColor whiteColor];
  }

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  return YES;
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

@end

`

**Comment by suhaspathak** [comment]
> What work for me,
> Just add
> `#import <Firebase.h>` to the AppDelegate.h as well

It is work for me. save lot of time. thanks

**Comment by suhaspathak** [comment]
> What work for me,
> Just add
> `#import <Firebase.h>` to the AppDelegate.h as well

It is work for me. save lot of time. thanks

**Comment by evangrim** [comment]
Make sure your `#import <Firebase.h>` is not inappropriately placed in an if block . :)

I accidentally put `#import <Firebase.h>` within `#if RCT_NEW_ARCH_ENABLED` block while upgrading;  I haven't enabled the new arch, so Firebase didn't load.
