### ISSUE TITLE
IOS recording file size is very large compare to Android 

### ISSUE THREAD

**Issue by jack-solutions** [react-native-camera/react-native-camera#3012]
# Question

**To Do First**
- [x] Take a look in the [README](https://github.com/react-native-community/react-native-camera/blob/master/README.md)
- [x] Take a look in the [docs](https://github.com/react-native-community/react-native-camera/blob/master/docs/RNCamera.md)
- [x] Take a look in the [QA](https://github.com/react-native-community/react-native-camera/blob/master/docs/QA.md)

**Ask your Question**
**IOS video recording is too large** 
maximum duration is 5 minutes and the file size getting is above **200 MB** with below config 
and same duration of recorded video file size is around **30 MB** in Android

**code :**
var options = {
        quality: Camera.Constants.VideoQuality['720p'],
        maxDuration: mediaConstants.videoMaxTime - 1,
        videoBitrate: 0.25 * 1000 * 1000,
      }
      if (Platform.OS == 'ios') {
        options.codec = Camera.Constants.VideoCodec.HVEC
      }
      await this.requestRecordPermission()
      const data = await this.camera.recordAsync(options)

please help to get IOS recording file size near to Android file size

Thanks in advance 
**Tags**

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate
> Want this issue to be resolved faster? Please consider adding a bounty to it https://issuehunt.io/repos/33218414

**Comment by ziiw** [comment]
I have the same issue. For a 2.77GB file, I will have :
- iOS: 2775040922 RNFS.stat.size
- Android : 806681600 RNFS.stat.size

RNFS version 2.16.6

**Comment by MarcoScabbiolo** [comment]
Please [ffprobe](https://ffmpeg.org/ffprobe.html) both videos and share the results so we can understand the reason behind the difference in size
