### ISSUE TITLE
Any plan for moving into CameraX version?

### ISSUE THREAD

**Issue by Balasnest** [react-native-camera/react-native-camera#3023]
# Feature-Request

**Describe the Feature**
Are we in the plan for integrating newer SDK lib - cameraX ? Actually I am [creating](https://stackoverflow.com/questions/64789211/camerax-view-in-react-native-unable-to-configure-camera) react native bridge for cameraX View. But facing some issues with the flow. Let me know if anybody managed to get it to work.

**Comment by renatobenks** [comment]
There's not work in progress yet, it would definitely be introduced in the next versions of rn-camera, once it will be completely re-written
