### ISSUE TITLE
firebase version 10.0.0  duplicate dependencies!!

### ISSUE THREAD

**Issue by methineeinkan** [react-native-camera/react-native-camera#3031]
# Bug Report

**Versions**
- Android:
"react-native-camera": "^3.40.0",
"react": "16.13.1",
"react-native": "0.63.3",

    "@react-native-firebase/analytics": "10.0.0",
    "@react-native-firebase/app": "10.0.0",
    "@react-native-firebase/crashlytics": "10.0.0",
    "@react-native-firebase/database": "10.0.0",
    "@react-native-firebase/firestore": "10.0.0",
    "@react-native-firebase/messaging": "10.0.0",
    "@react-native-firebase/perf": "10.0.0",
 
Duplicate class com.google.android.gms.internal.vision.zzbl found in modules jetified-firebase-ml-vision-face-model-17.0.2-runtime.jar 

<img width="970" alt="Screen Shot 2563-11-21 at 22 57 31" src="https://user-images.githubusercontent.com/40588602/99881640-81fede80-2c4d-11eb-915f-4b569ecc789e.png">

**Comment by Hilbertangers** [comment]
try
![image](https://user-images.githubusercontent.com/21299424/99962627-7d603480-2dcb-11eb-96f4-3059651e0997.png)

**Comment by methineeinkan** [comment]
> try
> ![image](https://user-images.githubusercontent.com/21299424/99962627-7d603480-2dcb-11eb-96f4-3059651e0997.png)

not work

**Comment by methineeinkan** [comment]
@Hilbertangers Not Work

**Comment by methineeinkan** [comment]
is work for me Go to react-native-camera => build-gradle => dependencies

 def googlePlayServicesVisionVersion = safeExtGet('googlePlayServicesVisionVersion', safeExtGet('googlePlayServicesVersion', '20.1.2'))

  //noinspection GradleDynamicVersion
  implementation 'com.facebook.react:react-native:+'  // From node_modules
  implementation "com.google.zxing:core:3.3.3"
  implementation "com.drewnoakes:metadata-extractor:2.11.0"
  generalImplementation "com.google.android.gms:play-services-vision:$googlePlayServicesVisionVersion"
  implementation "androidx.exifinterface:exifinterface:1.0.0"
  implementation "androidx.annotation:annotation:1.0.0"
  implementation "androidx.legacy:legacy-support-v4:1.0.0"
  mlkitImplementation "com.google.firebase:firebase-ml-vision:${safeExtGet('firebase-ml-vision', '24.0.3')}"
  mlkitImplementation "com.google.firebase:firebase-ml-vision-face-model:${safeExtGet('firebase-ml-vision-face-model', '20.0.1')}"

  implementation 'com.google.android.gms:play-services-vision-common:19.1.1'
  implementation "com.google.android.gms:play-services-vision-face-contour-internal:16.0.2"
  implementation 'com.google.android.gms:play-services-vision-image-label:18.0.5'

**Comment by SnaiNeR** [comment]
same for the iOS 
![image](https://user-images.githubusercontent.com/39980963/100270146-72e39d80-2f79-11eb-9363-ffbb954fb085.png)

**Comment by methineeinkan** [comment]
> same for the iOS
> ![image](https://user-images.githubusercontent.com/39980963/100270146-72e39d80-2f79-11eb-9363-ffbb954fb085.png)

try remove podfile.look and 
rm -rf ~/Library/Caches/CocoaPods
rm -rf Pods
rm -rf ~/Library/Developer/Xcode/DerivedData/*
pod deintegrate
pod setup

**Comment by SnaiNeR** [comment]
@methineeinkan it is not helped :-(
there is really conflict of dependencies, in android you resolve it by installing main version via gradle, in iOS this won't work

**Comment by SnaiNeR** [comment]
```
    implementation(project(':react-native-camera'),  {
        exclude group: "com.google.android.gms"
        exclude group: "com.google.firebase", module: "firebase-ml-vision-face-model"
    })
```
this changes in app/build.gradle also helped, without editing react-native-camera package

**Comment by DiMaNacho** [comment]
> same for the iOS
> ![image](https://user-images.githubusercontent.com/39980963/100270146-72e39d80-2f79-11eb-9363-ffbb954fb085.png)

Same!

**Comment by yvza** [comment]
> exclude group: "com.google.android.gms"
>         exclude group: "com.google.firebase", module: "firebase-ml-vision-face-model"

Hi @SnaiNeR , i still got this error:
 Duplicate class com.google.android.gms.internal.vision.zze found in modules play-services-vision-20.0.0-runtime.jar (com.google.android.gms:play-services-vision:20.0.0) and play-services-vision-common-19.1.0-runtime.jar (com.google.android.gms:play-services-vision-common:19.1.0)

can u help me

**Comment by rakicluca** [comment]
> def googlePlayServicesVisionVersion = safeExtGet('googlePlayServicesVisionVersion', safeExtGet('googlePlayServicesVersion', '20.1.2'))

Where is this path??? Can I update using che "Project Structure" function in Android Studio?
