### ISSUE TITLE
Broken CI

### ISSUE THREAD

**Issue by SimonErm** [react-native-camera/react-native-camera#3032]
# Bug Report

The CI-Setup seems to be broken which results in unfinished checks for PRs.
I think circleci is configured for the old repository.
Who owns the rights to change this?

**Comment by MateusAndrade** [comment]
Hi @SimonErm, because of a change in the organization that this repo was, probably the CI set-up is missing an Org/Plan set-tup at CircleCI. I can have a look at this, but maybe we will need some help with the set-up at CircleCI.

**Comment by SimonErm** [comment]
I never worked with circleci before, but i can try to help.

**Comment by SimonErm** [comment]
Any news on this or something i can do to help?
Would be great if we could merge some of the PRs soon.

**Comment by MateusAndrade** [comment]
> Any news on this or something i can do to help?
> Would be great if we could merge some of the PRs soon.

Hi @SimonErm , I was able to set the project at CircleCI again. As far as I know, I think everything should be working(we still need to test the deploy to npm, etc). You can look at the build [here](https://app.circleci.com/pipelines/github/react-native-camera/react-native-camera).
