### ISSUE TITLE
Make onTextRecognized method work with rectOfInterest

### ISSUE THREAD

**Issue by tungduonghgg123** [react-native-camera/react-native-camera#3042]
# Question

**To Do First**
- [ yep ] Take a look in the [README](https://github.com/react-native-community/react-native-camera/blob/master/README.md)
- [ yep ] Take a look in the [docs](https://github.com/react-native-community/react-native-camera/blob/master/docs/RNCamera.md)
- [ yep ] Take a look in the [QA](https://github.com/react-native-community/react-native-camera/blob/master/docs/QA.md)

**Ask your Question**

Hi, so I'm trying to make a PR for this library. In this PR, I want the `rectOfInterest` property to take effect on the text recognization as well. I'm doing it for the Android platform first, then iOS. For this topic, I'm seeking your consultation on the Android only.
I aim to crop the data ( take out the data on the left and top of the (x, y) coordinates) before passing it to the `buildFrame` method:
```  @Override
  protected SparseArray<TextBlock> doInBackground(Void... ignored) {
    if (isCancelled() || mDelegate == null) {
      return null;
    }
    mTextRecognizer = new TextRecognizer.Builder(mThemedReactContext).build();
    RNFrame frame = RNFrameFactory.buildFrame(mImageData, mWidth, mHeight, mRotation);
    return mTextRecognizer.detect(frame.getFrame());
  }
```
`mImageData` is  a `byte []` variable. It seems impossible to crop it in this form so I try to convert it to a `Bitmap` then take advantage of the approach mentioned in this topic: [android-crop-center-of-bitmap](https://stackoverflow.com/questions/6908604/android-crop-center-of-bitmap)
But when I try to convert it do `Bitmap`, I got `null`.
`Bitmap srcBmp = BitmapFactory.decodeByteArray(mImageData, 0, mImageData.length);`
I'm currently stuck in here, can you guys please help. Thanks! This is my first time contributing to the open source world so please be patient with me.
**Tags**

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate
> Want this issue to be resolved faster? Please consider adding a bounty to it https://issuehunt.io/repos/33218414

**Comment by cmd08010** [comment]
I am interested. I am going to try and implement this and will report back if I have any success!
