### ISSUE TITLE
after stopRecording the app freezes in android

### ISSUE THREAD

**Issue by marquina-abreu** [react-native-camera/react-native-camera#3056]
# Bug Report
 After stopRecording the app freezes in android
**To Do First**

- [x] Did you try latest release?
- [x] Did you try master?
- [x] Did you look for existing matching issues?

**Platforms**
android

**Versions**
react-native: "0.63.2"
react-native-camera: "3.40.0"

- Android: 10 api 29
- iOS:
- react-native-camera: "3.40.0"
- react-native: "0.63.2"
- react: "16.13.1"
  

**Description/Current Behaviour**

**Expected Behaviour**

**Steps to Reproduce**

**Additionals**

> Love react-native-camera? Please consider supporting our collective: 👉 https://opencollective.com/react-native-camera/donate
> Want this issue to be resolved faster? Please consider adding a bounty to it https://issuehunt.io/repos/33218414

**Comment by fansmc** [comment]
三星SM-G9860 机器上遇到了同样的问题

**Comment by Hermanyo** [comment]
Same issue, anyone solved it?
