### ISSUE TITLE
QR Codes not recognized in some Huawei devices

### ISSUE THREAD

**Issue by jeremy-ingenuity** [react-native-camera/react-native-camera#3058]
# Bug Report

**To Do First**

- [x] Did you try latest release?
- [x] Did you try master?
- [x] Did you look for existing matching issues?

**Platforms**

Android

**Versions**

- Android: 10
- iOS:
- react-native-camera: 3.40.0
- react-native: 0.63.3
- react: 16.13.1
- react-navigation: 5

**Description/Current Behaviour**
* Correctly implemented QR scanner using `react-native-camera`, but some phones were not able to detect QR codes using the library:
- Huawei P10
- Huawei Y6P
- Huawei 8p
- Huawei 7i

**Comment by manojudeshika93** [comment]
This issue is still present. Anyone has any idea to fix this?

**Comment by manojudeshika93** [comment]
Found a solution for this issue. 
Just add these configs, 
https://github.com/react-native-camera/react-native-camera/blob/HEAD/docs/installation.md#android

**Comment by jeremy-ingenuity** [comment]
@manishkumar03 I resorted to using `expo-camera`, works better and faster 👍
