### ISSUE TITLE
Could not resolve com. Google. Firebase: firebase - ml - common: [17.0.0].It started up normally before, but it won't start up today

### ISSUE THREAD

**Issue by caijiami** [react-native-camera/react-native-camera#3059]
Could not determine the dependencies of task ':app:processDebugResources'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.google.firebase:firebase-ml-common:[17.0.0].

**Comment by caijiami** [comment]
@almost @miracle2k @christocracy @alexdunae the latest version

**Comment by xunaizhong20** [comment]
me too

**Comment by Diordrzy** [comment]
> @almost @miracle2k @christocracy @alexdunae the latest version

How did you solve this problem？
