### ISSUE TITLE
Changing camera permission in the android system preference while the app is on background camera remain not authorized

### ISSUE THREAD

**Issue by brendan1809** [react-native-camera/react-native-camera#3061]
# Question

**To Do First**
- [x] Take a look in the [README](https://github.com/react-native-community/react-native-camera/blob/master/README.md)
- [x] Take a look in the [docs](https://github.com/react-native-community/react-native-camera/blob/master/docs/RNCamera.md)
- [x] Take a look in the [QA](https://github.com/react-native-community/react-native-camera/blob/master/docs/QA.md)

**Ask your Question**
Android 10
react-native-camera : 0.63.0
react-native : 0.63.4
Currently i am using `react native permission` and one of the library's function  `openSettings` https://github.com/zoontek/react-native-permissions#opensettings
After allowing the camera permission in the system and navigate back to the app, the camera remains `notAuthorizedView`
```
notAuthorizedView={
                  <View style={{ flex: 1, alignItems: "center", justifyContent: "center" }}>
                    <TouchableOpacity onPress={() => checkPermission()}>
                      <Text style={{ color: "#007bff", fontSize: 18 }}>Go To Setting</Text>
                    </TouchableOpacity>
                  </View>
                }
```
**Tags**

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate
> Want this issue to be resolved faster? Please consider adding a bounty to it https://issuehunt.io/repos/33218414

**Comment by xuezhimin** [comment]
hello , Excuse me. Has the problem been solved ？
