### ISSUE TITLE
Barcode recognition code128 too slow

### ISSUE THREAD

**Issue by liliiilillil** [react-native-camera/react-native-camera#3063]
i'm using the latest version 3.40.0
android device
couldn't read code-128 rapidly

**Comment by tewarig** [comment]
could you please provide more information? 

- Which dependencies you are using? 
- whether you are using managed workflow(expo) or bare workflow (plane react-native) 
- which android device you are using?

**Comment by ajaysaini-sgvu** [comment]
I am also facing same issue. Any way to resolve this ?
