### ISSUE TITLE
Firebase ML version lib class match issue

### ISSUE THREAD

**Issue by rajeev-tomar06** [react-native-camera/react-native-camera#3068]
# Bug Report

We are using 'https://rnfirebase.io/' for PushNotification & Analytics. After upgrading the lib we are getting the build issue on Android platform for duplicate class error. It's might be both lib camera & firebase using the firebase ML vision lib. How can we handle this situation. Can we exclude this lib -"firebase ML vision" somehow.

**Comment by russelRajitha** [comment]
@rajeev-tomar06 do you have any specific versions of firebase react native and other stuff?

**Comment by rajeev-tomar06** [comment]
@russelRajitha Please find the details below.
"react-native-camera": "^3.31.1",
========================
    "@react-native-firebase/analytics": "^10.3.1",
    "@react-native-firebase/app": "^10.3.0",
    "@react-native-firebase/messaging": "^10.3.1",
=======================================

**Comment by Shashank-Yara** [comment]
+1

**Comment by HLeshan** [comment]
+1

**Comment by Muhammad-Wasi** [comment]
> manage to fix the issue by adding following
> 
> ```
>    implementation (project(':react-native-camera')) {
>         exclude group: "com.google.android.gms"
>         exclude group: "com.google.android.gms", module: "play-services-vision"
>         exclude group: "com.google.firebase", module: "firebase-ml-vision-face-model"
>     }
> 
>     implementation ("com.google.firebase:firebase-ml-vision:19.0.3") {
>         force = true;
>     }
>     implementation ("com.google.firebase:firebase-ml-vision-face-model:17.0.2") {
>         force = true;
>     }
> ```

Worked in my case <3

**Comment by tanmoythander** [comment]
> manage to fix the issue by adding following
> 
> ```
>    implementation (project(':react-native-camera')) {
>         exclude group: "com.google.android.gms"
>         exclude group: "com.google.android.gms", module: "play-services-vision"
>         exclude group: "com.google.firebase", module: "firebase-ml-vision-face-model"
>     }
> 
>     implementation ("com.google.firebase:firebase-ml-vision:19.0.3") {
>         force = true;
>     }
>     implementation ("com.google.firebase:firebase-ml-vision-face-model:17.0.2") {
>         force = true;
>     }
> ```

Added this in **app/build.gradle** inside **dependencies** and it worked like magic !!!

**Comment by roxlu** [comment]
For anyone who wants to know a bit more about this issue, I wrote down some [notes while looking into this here][notes].

[notes]: https://gist.github.com/roxlu/89914461faf0f8571f833b47c27c8c75
