### ISSUE TITLE
Camera get a crash on certains android / mobile phone models

### ISSUE THREAD

**Issue by nlaitanatix** [react-native-camera/react-native-camera#3077]
# Bug Report
I got the next error: 
```
Attempt to invoke virtual method 'int com.google.android.cameraview.Size.getWidth()' on a null object reference
com.google.android.cameraview.Camera1.adjustCameraParameters
```
When an user try to use the camera on my app. Only he gets that error, me on my phone couldn't reproduce it, another person with the same android version (7 - Nougat) also couldn't reproduce.

- [NO] Did you try latest release?
- [NO] Did you try master?
- [YES] Did you look for existing matching issues?

- Android: **7.1.2**
- react-native-camera: **3.4.0**
- react-native: **0.61.5**
- react: **16.12.0**
- react-navigation: **4.0.10**
- mobile phone: LG K9

**Comment by piccinnigius** [comment]
same problem here but with videoBitrate
