### ISSUE TITLE
I have a problem with flashmode if i keep camera open and take multiple images. 

### ISSUE THREAD

**Issue by ThisIsRandom** [react-native-camera/react-native-camera#3085]
I have a problem. If i open the camera and take a picture, it no longer react to changing the flashmode? 
I can change the flashmode no problem, but once picture is captured and i want to capture another one, it doesnt react to the state change. (I dont close the camera in between)

The videocamera part has no problem.

Anyone else had this problem, and might be able to help me out? :) Thanks in advance.

**Comment by fabriziobertoglio1987** [comment]
when you take the image it gives you a preview
then it goes back in camera mode

maybe something is causing issues there
