### ISSUE TITLE
Permission issue

### ISSUE THREAD

**Issue by zjw199011** [react-native-camera/react-native-camera#3098]
I am not sure am I the only one facing this issue or not.

I setted up the androidCameraPermissionOptions in RNCamera.
It crashed the Android App for the new user, because they didn't grant the permission to use the camera.

I manually add the PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.CAMERA) before render the RNCamera.
It works.

**Comment by MateusAndrade** [comment]
HI @zjw199011, would you mind sharing which rn version, android(your user was using), and rn-camera are you using?

**Comment by zjw199011** [comment]
> HI @zjw199011, would you mind sharing which rn version, android(your user was using), and rn-camera are you using?

Sure.

    "react": "16.13.1",
    "react-native": "0.63.4",
    "react-native-camera": "^3.42.0",

When I using the react-native-camera 3.30, it works fine.
So, I am not sure is it only happened to me or not.


I tested couple android device. If they didn't provided the permission before like a new user, it will crash the app.
Is it required to check the permission then navigate to RNCamera or adding androidCameraPermissionOptions is good enough?

**Comment by zjw199011** [comment]
I also have a question about the barcode scaning. There are couple barcodes won't recognize by the framework even they are the same type barcode with others. Can you give me some idea why it happened? How can I test or solve the issue?  Thanks

**Comment by MateusAndrade** [comment]
> Is it required to check the permission then navigate to RNCamera or adding androidCameraPermissionOptions is good enough?

As far as I remember, using the `androidCameraPermissionOptions` options is supposed to ask the device for permission, which would make checking for this redundant. 

Btw, when you check for camera permission before rendering the camera, and the user agrees this doesn't crash your app? Maybe we got a change at the android permissions between `3.30` and `3.42` 🤔 .

> I also have a question about the barcode scaning. There are couple barcodes won't recognize by the framework even they are the same type barcode with others. Can you give me some idea why it happened? How can I test or solve the issue? Thanks

Do you have any examples? I had this problem scanning specific barcodes, but most of the time it worked. On android, we use this [library](https://github.com/zxing/zxing) if you don't have firebase ML-enabled.

**Comment by zjw199011** [comment]
> > Is it required to check the permission then navigate to RNCamera or adding androidCameraPermissionOptions is good enough?
> 
> As far as I remember, using the `androidCameraPermissionOptions` options is supposed to ask the device for permission, which would make checking for this redundant.
> 
> Btw, when you check for camera permission before rendering the camera, and the user agrees this doesn't crash your app? Maybe we got a change at the android permissions between `3.30` and `3.42` 🤔 .
> 

**Yep. It worked perfectly before. I think it was passing the title and message into RNCamera before not the permission object.**



> > I also have a question about the barcode scaning. There are couple barcodes won't recognize by the framework even they are the same type barcode with others. Can you give me some idea why it happened? How can I test or solve the issue? Thanks
> 
> Do you have any examples? I had this problem scanning specific barcodes, but most of the time it worked. On android, we use this [library](https://github.com/zxing/zxing) if you don't have firebase ML-enabled.


**Yep. It works on most of the barcode, but there are still some barcode cannot recoginized by the framework.
Let me find some examples. I didn't turn on the ML kit framework when I doing these test. But I also tested these barcode with firebase ML kit. It is not working too. ** 

![abbott1 (1)](https://user-images.githubusercontent.com/28021745/107406785-d2f8d300-6ad6-11eb-85f5-60e28aaad521.jpeg)

![medtronic1](https://user-images.githubusercontent.com/28021745/107406847-ea37c080-6ad6-11eb-8189-71e6c0cc1ae4.jpeg)

**Comment by MateusAndrade** [comment]
> Let me find some examples. I didn't turn on the ML kit framework when I doing these test. But I also tested these barcode with firebase ML kit. It is not working too. **

Do you which format these barcodes use?

**Comment by zjw199011** [comment]
> > **Yep. It worked perfectly before. I think it was passing the title and message into RNCamera before not the permission object.**
> 
> Would you mind testing this with our example app? Probably it's related to this code or subsequent parts that deal with permission for Android 🤔
> 
> https://github.com/react-native-camera/react-native-camera/blob/7cb797916e995fa1d4b859b4287b5c46eb21b0b1/src/RNCamera.js#L56-L65
> 

**Sure. I can test it.**

> > Let me find some examples. I didn't turn on the ML kit framework when I doing these test. But I also tested these barcode with firebase ML kit. It is not working too. **
> 
> Do you which format these barcodes use?

**I think they are all both Code-128. That's why I really confused. Most of the Code-128 barcodes works fine. Only a few didn't work. I don't know what's the difference between them. They are both the same type. Did you try these barcode which I posted?Does it works? I used another App from the Apple Store/Google Store to test them. They are all code-128. They can read these barcodes.**

**Comment by zjw199011** [comment]
> > **Yep. It worked perfectly before. I think it was passing the title and message into RNCamera before not the permission object.**
> 
> Would you mind testing this with our example app? Probably it's related to this code or subsequent parts that deal with permission for Android 🤔
> 
> https://github.com/react-native-camera/react-native-camera/blob/7cb797916e995fa1d4b859b4287b5c46eb21b0b1/src/RNCamera.js#L56-L65
> 
> > Let me find some examples. I didn't turn on the ML kit framework when I doing these test. But I also tested these barcode with firebase ML kit. It is not working too. **
> 
> Do you which format these barcodes use?

I am not sure how can I try with that? Do you mean add the permission check manually?

Here is what it showed in my App.
It shows the modal, but it crashed at the same time.
Maybe I didn't use it correctly? 
But it didn't happen before.

![image](https://user-images.githubusercontent.com/28021745/107984194-69c10600-6f95-11eb-8899-cf431931de65.png)

**Comment by okevino47** [comment]
Hi, i m facing the same problem... everytime i try to render rncamera (with or without androidPermission) my app crash.
I don t provide any code sample cause it s exactly the same code sample in this thread that i am using.

Does anyone has any news about it ?
