### ISSUE TITLE
Photo full dimensions

### ISSUE THREAD

**Issue by GaspardC** [react-native-camera/react-native-camera#3112]
How can I have a photo with the full resolution ?

Here is a screenshot of the 2 photos, one taken with the native camera and one with react-native-camera.

<img width="1262" alt="Capture d’écran 2021-02-15 à 15 07 24" src="https://user-images.githubusercontent.com/9252579/107957938-9b3fce80-6fa1-11eb-9eef-aec889762d9c.png">

in the app the RNCamera is taken with the full width and height = width * 4/3

thanks

**Comment by cristianoccazinsp** [comment]
On iOS, the camera uses the screen's aspect ratio to resize/adjust the pictures. So if you want perfectly "native" photos, you need to make sure your camera component renders a perfect 4:3 or 16:9 rectangle.
