### ISSUE TITLE
 'Resolve dependencies of :react-native-camera:classpath' is slow

### ISSUE THREAD

**Issue by a1005342094** [react-native-camera/react-native-camera#3123]
When react-native run-android to resolve dependencies, it is very slow.
It runs fast when there is no network，But when packing need network, which bothers me very much.
Is there any way to solve it?

**Comment by YanmaY** [comment]
@a1005342094 你的问题解决了吗兄弟，我也遇到了一样的情况，断网之后构建飞快，联网之后构建最少要40分钟

**Comment by Symous** [comment]
@YanmaY Old brother, how did you solve this?
