### ISSUE TITLE
Type for "cameraId" is undefined

### ISSUE THREAD

**Issue by lxender** [react-native-camera/react-native-camera#3126]
# Bug Report

The property "cameraId" is undefined in [index.d.ts](https://github.com/react-native-camera/react-native-camera/blob/master/types/index.d.ts) but is accepted by the component.

I tested this with the latest version.

![image](https://user-images.githubusercontent.com/20384895/109036835-4f400880-76ca-11eb-83f6-2fc2dbd2f730.png)

**Comment by cristianoccazinsp** [comment]
Looks like a typings/ts missing prop? Can you provide a PR to include it in `index.d.tx` ? :)
