### ISSUE TITLE
onGoogleVisionBarcodesDetected with rectOfInterest does not work

### ISSUE THREAD

**Issue by bonfimjustino7** [react-native-camera/react-native-camera#3131]
# Bug Report

**To Do First**

- [x ] Did you try latest release?
- [ x] Did you try master?
- [ x] Did you look for existing matching issues?

**Platforms**

**Versions**

- Android:
- iOS:
- react-native-camera:
- react-native:
- react:
  

**Description/Current Behaviour**

Barcode reading with the onGoogleVisionBarcodesDetected rectOfInterest method
from RNCamera don't work together

**Expected Behaviour**

**Steps to Reproduce**

**Additionals**

> Love react-native-camera? Please consider supporting our collective: 👉 https://opencollective.com/react-native-camera/donate
> Want this issue to be resolved faster? Please consider adding a bounty to it https://issuehunt.io/repos/33218414

**Comment by renatobenks** [comment]
@bonfimjustino7 can you provide examples of code about this?
