### ISSUE TITLE
How to get the file name after taking the photo?

### ISSUE THREAD

**Issue by Yandamuri** [react-native-camera/react-native-camera#3139]
Below is the object which response after taking photo

![camres](https://user-images.githubusercontent.com/31983789/110212635-5df49f80-7ec2-11eb-937c-92e6d9284556.PNG)

is it possible to get the file name separately? Or at least some one help me to extract the file name from uri?

**Comment by IacoCesar** [comment]
? The filename is blabla.jpg, use string split for this
