### ISSUE TITLE
How to adjust iso, whitebalance and exposure for Android devices only?

### ISSUE THREAD

**Issue by adityar15** [react-native-camera/react-native-camera#3140]
I am building a react native app. Is there any way to adjust iso, white balance, and exposure of the image/camera through code using react native camera?

**Comment by fabriziobertoglio1987** [comment]
the available functionality https://react-native-camera.github.io/react-native-camera/docs/rncamera#whitebalance

otherwise I suggest you to fork the project and add the functionalities you need
