### ISSUE TITLE
takePictureAsync doesn't resolve in android emulator when the camera is emulated with webcam0

### ISSUE THREAD

**Issue by reach1dev** [react-native-camera/react-native-camera#3141]
# Bug Report

**Platforms**

Android

**Versions**

- Android: compileSdkVersion(28, 29: both tried), buildToolsVersion(28.0.3)
- react-native-camera: 3.43.0
- react-native: 0.62.1
- react: 16.11.0

**Description/Current Behaviour**
Rendered the camera with the following code.
```
<RNCamera
          ref={cam => {
            this.camera = cam;
          }}
          style={styles.preview}
          captureAudio={false}
          trackingEnabled
          flashMode={
            this.state.torch
              ? RNCamera.Constants.FlashMode.torch
              : RNCamera.Constants.FlashMode.off
          }
          autofocus={RNCamera.Constants.AutoFocus.on}
          onGoogleVisionBarcodesDetected={object =>
            this.state.canDetectQR
              ? this.qrRecognized(object)
              : this.state.canDetectBarcode
              ? this.barcodeRecognized(object)
              : null
          }
          aspect={1}
          googleVisionBarcodeType={
            this.state.canDetectQR
              ? RNCamera.Constants.GoogleVisionBarcodeDetection.BarcodeType
                  .QR_CODE
              : RNCamera.Constants.GoogleVisionBarcodeDetection.BarcodeType.ALL
          }
          onTextRecognized={
            this.state.canDetectText ? this.textRecognized : null
          }
        />
```
And call the takePictureAsync with the following options.
```
const options = {
          quality: 0.5,
          base64: true,
          fixOrientation: true,
          orientation:
            Platform.OS === 'android' ? 'landscapeLeft' : 'landscapeRight',
        };
        const data = await this.camera.takePictureAsync(options);
```
But the app doesn't move forward to the next line as the returned promise of takePictureAsync doesn't resolve it.
Tested in the android emulator (sdk:30) with the camera simulating the webcam image using ManyCams.

**Expected Behaviour**

takePictureAsync should resolve the image captured so my code should go forward to the next line.

**Additionals**

![image](https://user-images.githubusercontent.com/78322772/110446691-80f49e80-80d0-11eb-9600-84b3d13617e8.png)

If this code moves forward, this screenshot should go to the next screen but stuck.

Thanks.

**Comment by fabriziobertoglio1987** [comment]
I would avoid using webcam0 for now

**Comment by snowwaltz** [comment]
Hi @fabriziobertoglio1987, what is the solution for this issue?

**Comment by jackkrone** [comment]
I had the exact same issue when using VirtualScene or Webcam0 for the camera. On a physical android device everything works fine, but on the emulator the camera would freeze when I took a photo.

What worked for me:
 Switch the camera option to "Emulated" in the device (AVD) settings. Let me know if you need help finding this setting (it's in advanced settings)
<img width="573" alt="Screenshot 2023-04-27 at 11 33 41 AM" src="https://user-images.githubusercontent.com/37680054/234912561-f29bd93a-de93-4619-bf38-3a3b84ce5883.png">
