### ISSUE TITLE
modelParams props is missing 

### ISSUE THREAD

**Issue by bhaveshpatel1** [react-native-camera/react-native-camera#3146]
I am using this library with latest version : https://www.npmjs.com/package/react-native-camera-tflite
But app got crashed while running it.
And this parameter (modelParams) is also missing.

![Screenshot 2021-03-11 at 6 21 55 PM](https://user-images.githubusercontent.com/66124824/110791952-d380b700-8298-11eb-8f73-e9fcaeebaf76.png)

**Comment by fabriziobertoglio1987** [comment]
the repository has been archived by the owner https://github.com/ppsreejith/react-native-camera-tflite
