### ISSUE TITLE
Is it possible to access PRO mode options?

### ISSUE THREAD

**Issue by M1ck0** [react-native-camera/react-native-camera#3148]
# Question

**Ask your Question**
My phone has multiple back cameras. Is it possible to choose between them? And also, is it possible to choose pro mode (to edit things like shutter speed, ISO...)

**Tags**

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate
> Want this issue to be resolved faster? Please consider adding a bounty to it https://issuehunt.io/repos/33218414

**Comment by sdiazj** [comment]
any news on this?

**Comment by M1ck0** [comment]
No. Sadly nothing for now
