### ISSUE TITLE
how to scan small-scale QRcode?

### ISSUE THREAD

**Issue by wqxwqx** [react-native-camera/react-native-camera#3155]
# Question

**To Do First**
- [ ] Take a look in the [README](https://github.com/react-native-community/react-native-camera/blob/master/README.md)
- [ ] Take a look in the [docs](https://github.com/react-native-community/react-native-camera/blob/master/docs/RNCamera.md)
- [ ] Take a look in the [QA](https://github.com/react-native-community/react-native-camera/blob/master/docs/QA.md)

**Ask your Question**

**Tags**

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate
> Want this issue to be resolved faster? Please consider adding a bounty to it https://issuehunt.io/repos/33218414

**Comment by fabriziobertoglio1987** [comment]
explained here https://github.com/react-native-camera/react-native-camera/pull/2766

it is the main weakness of this library, as the existing rectOfInterest prop does not actually limit the scanning area in a precise/mathematical correct calculation

the functinality is pretty complex, more info in the pr https://github.com/react-native-camera/react-native-camera/pull/2766

**Comment by wqxwqx** [comment]
thank you.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "react-native-camera/react-native-camera"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月31日(星期三) 晚上9:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [react-native-camera/react-native-camera] how to scan small-scale QRcode? (#3155)





 
explained here #2766
 
it is the main weakness of this library, as the existing rectOfInterest prop does not actually limit the scanning area in a precise/mathematical correct calculation
 
the functinality is pretty complex, more info in the pr #2766
