### ISSUE TITLE
How to remove mic permission from ios? 

### ISSUE THREAD

**Issue by ammartariq100** [react-native-camera/react-native-camera#3167]
Hi,
I am trying to remove microphon permission from the the project, but appstore is rejecting my app 
<img width="688" alt="Screenshot 2021-03-31 at 10 01 30 PM" src="https://user-images.githubusercontent.com/49687532/113182734-ad817d80-926c-11eb-887e-f5e7fccaa066.png">

**Comment by Mushu2a** [comment]
You have to include permission
`
<key>NSMicrophoneUsageDescription</key>
<string>Your message to user when the microphone is accessed for the first time</string>`

Or just use **captureAudio** to false if you don't want to use it

Source
https://github.com/react-native-camera/react-native-camera/blob/master/docs/installation.md#requirements
https://github.com/react-native-camera/react-native-camera/blob/master/docs/RNCamera.md
