### ISSUE TITLE
External USB Camera Support

### ISSUE THREAD

**Issue by 101614855** [react-native-camera/react-native-camera#3171]
# Question

Hey Guys, 

I'm new to react native and as one of my learning projects, i am trying to build an app to use with a cheap USB endoscope (micro usb webcam). 

I know there was a previous project that tried to integrate with this project, but it appears to be fairly out of date (last commit was 3 years ago) : https://www.npmjs.com/package/react-native-uvc-camera

Is there any chance of this project supporting external USB cameras? if not would anyone be able to point me in the right direction in getting a usb camera to work with this library?

Thanks

**Comment by anmolmalik97** [comment]
Any updates on this issue?
