### ISSUE TITLE
Text recognition - Migrate to MLKit instead of firebase?

### ISSUE THREAD

**Issue by cristianoccazinsp** [react-native-camera/react-native-camera#3192]
# Feature-Request

**Describe the Feature**
Text recognition currently requires a complicated setup with firebase. However, it could be implemented with less boilerplate by using Google's MLKit.

For instance, https://github.com/agoldis/react-native-mlkit-ocr uses that approach and requires 0 firebase setup. 

In fact, https://firebase.google.com/docs/ml-kit/recognize-text recommends this approach (no firebase setup) for offline detection, which I believe is what currently being used. 

**Possible Implementations**
Perhaps link directly to https://github.com/agoldis/react-native-mlkit-ocr or vendor it so it can be called directly from RNCamera.

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate
> Want this feature to be resolved faster? Please consider adding a bounty to it https://issuehunt.io/repos/33218414

**Comment by trackwell-mike** [comment]
Curious if anyone has implemented this update?
