### ISSUE TITLE
Rare iOS crash - startRunning may not be called between calls to beginConfiguration

### ISSUE THREAD

**Issue by cristianoccazinsp** [react-native-camera/react-native-camera#3230]
# Bug Report

**To Do First**

- [X] Did you try latest release?
- [X] Did you try master?
- [X] Did you look for existing matching issues?

**Platforms**

iOS

**Versions**

- iOS: 14.x
- react-native-camera: 3.43.8
- react-native: 0.62.2
- react: 16.14

**Description/Current Behaviour**
There seems to be an odd iOS race condition when recording and/or changing camera settings that will cause the following crash from time to time:
```
NSGenericException: *** -[AVCaptureSession startRunning] startRunning may not be called between calls to beginConfiguration and commitConfiguration

0  CoreFoundation          ___exceptionPreprocess
1  libobjc.A.dylib         _objc_exception_throw
2  AVFCapture              -[AVCaptureSession startRunning]
```

**Expected Behaviour**
No crash

**Steps to Reproduce**
I haven't been able to reproduce the exact case yet as it comes from the error reporting tool, but I think it may happen when calling `recordAsync` and either the following happens in between the record start call and the actual recording start:
- A phone call or something interrupts the audio session, firing the audio interrupt events
- Camera type (or ID) changes right between the record call
- `sessionRuntimeError` fired for some reason and tried to re-start the session

I will debug further, but it's so rare that it may take time.

> Love react-native-camera? Please consider supporting our collective: 👉 https://opencollective.com/react-native-camera/donate
> Want this issue to be resolved faster? Please consider adding a bounty to it https://issuehunt.io/repos/33218414

**Comment by azban** [comment]
Also running into this issue sporadically, but with expo-camera instead of react-native-camera. Don't know if this is the right place, but don't see any issues in expo and figure it's the same issue.

**Versions:**
- iOS: 15.1
- expo-camera: 11.2.2
- react-native: 0.63.4
- react: 16.13.1
