### ISSUE TITLE
RNCamera onFacesDetected: some android devices not working

### ISSUE THREAD

**Issue by minhngo111196** [react-native-camera/react-native-camera#3233]
# Question
I am working on a feature that uses react-native-camera's onFacesDetected function, but on many Samsung devices it works fine and some others like Samsung Note 8, Xiaomi Redmi Pro 8, Vsmart Joy 3, .. . does not detect the user's face. onFacesDetected does not return any events.

Here 's my code
<RNCamera
          ref={ref => { this.camera = ref }}
          faceDetectionMode={RNCamera.Constants.FaceDetection.Mode.accurate}
          onFacesDetected={response => this.handleFaceDetected(response)} // not working on some android device ...
          onFaceDetectionError={response => this.handleFaceDetectedError(response)}
          faceDetectionClassifications={RNCamera.Constants.FaceDetection.Classifications.all}
          style={styles.preview}
          type={RNCamera.Constants.Type.front}
          captureAudio={false}
/>

**Comment by yamila-fraiman** [comment]
Same issue any idea?

**Comment by JE-Zenarosa** [comment]
onfacesdetected crashes my app. any solution?

**Comment by NiraliRadadiya** [comment]
same issue here.....any idea?
