### ISSUE TITLE
Option mirrorVideo from recordAsync() not work on Android (recording video).

### ISSUE THREAD

**Issue by zhaopenghai** [react-native-camera/react-native-camera#3234]
# Bug Report

**To Do First**

- [ ] Did you try latest release?
- [ ] Did you try master?
- [ ] Did you look for existing matching issues?

**Platforms**

Option mirrorVideo from recordAsync() not work on Android (recording video).

**Versions**
- Android:
- react-native-camera: ^3.43.8
- react-native:0.63.4
- react:16.11.0

**Description/Current Behaviour**

**Expected Behaviour**

Video should be mirrored.

**Steps to Reproduce**

Record a video on Android device with option mirrorVideo set to true.

**Additionals**

> Love react-native-camera? Please consider supporting our collective: 👉 https://opencollective.com/react-native-camera/donate
> Want this issue to be resolved faster? Please consider adding a bounty to it https://issuehunt.io/repos/33218414

**Comment by pragadeeshk** [comment]
@zhaopenghai Facing exactly the same issue. Any update/workaround?
