### ISSUE TITLE
React Natice Camera Build Failure

### ISSUE THREAD

**Issue by RavikumarRapolu** [react-native-camera/react-native-camera#3235]
Iam getting below errors after installing React native camera , Can any one help me pls

Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
[Fatal Error] metadata-extractor-2.11.0.pom:2:1: Content is not allowed in prolog.
[Fatal Error] legacy-support-v4-1.0.0.pom:2:1: Content is not allowed in prolog.
[Fatal Error] legacy-support-v4-1.0.0.pom:2:1: Content is not allowed in prolog.
[Fatal Error] core-3.3.3.pom:2:1: Content is not allowed in prolog.
[Fatal Error] exifinterface-1.3.2.pom:2:1: Content is not allowed in prolog.
[Fatal Error] exifinterface-1.3.2.pom:2:1: Content is not allowed in prolog.

FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
Could not resolve androidx.legacy:legacy-support-v4:1.0.0.
Required by:
project :app
project :app > project :react-native-camera
> Could not resolve androidx.legacy:legacy-support-v4:1.0.0.
> Could not parse POM https://dl.google.com/dl/android/maven2/androidx/legacy/legacy-support-v4/1.0.0/legacy-support-v4-1.0.0.pom
> Content is not allowed in prolog.
> Could not resolve androidx.legacy:legacy-support-v4:1.0.0.
> Could not parse POM https://maven.google.com/androidx/legacy/legacy-support-v4/1.0.0/legacy-support-v4-1.0.0.pom
> Content is not allowed in prolog.
Could not resolve com.drewnoakes:metadata-extractor:2.11.0.
Required by:
project :app
project :app > project :react-native-camera
> Could not resolve com.drewnoakes:metadata-extractor:2.11.0.
> Could not parse POM https://jcenter.bintray.com/com/drewnoakes/metadata-extractor/2.11.0/metadata-extractor-2.11.0.pom
> Content is not allowed in prolog.
Could not resolve com.google.zxing:core:3.3.3.
Required by:
project :app > project :react-native-camera
> Could not resolve com.google.zxing:core:3.3.3.
> Could not parse POM https://jcenter.bintray.com/com/google/zxing/core/3.3.3/core-3.3.3.pom
> Content is not allowed in prolog.
Could not resolve androidx.exifinterface:exifinterface:1.3.2.
Required by:
project :app > project :react-native-camera
> Could not resolve androidx.exifinterface:exifinterface:1.3.2.
> Could not parse POM https://dl.google.com/dl/android/maven2/androidx/exifinterface/exifinterface/1.3.2/exifinterface-1.3.2.pom
> Content is not allowed in prolog.
> Could not resolve androidx.exifinterface:exifinterface:1.3.2.
> Could not parse POM https://maven.google.com/androidx/exifinterface/exifinterface/1.3.2/exifinterface-1.3.2.pom
> Content is not allowed in prolog.

**Comment by MateusAndrade** [comment]
Hi @RavikumarRapolu, which version are you using?
