### ISSUE TITLE
iPhone X takePictureAsync Not Working

### ISSUE THREAD

**Issue by mronline** [react-native-camera/react-native-camera#3238]
# Bug Report

**To Do First**

- [x] Did you try latest release?
- [x] Did you try master?
- [x] Did you look for existing matching issues?

**Platforms**

iOS

**Versions**

- iOS: 14.4.2
- react-native-camera: 3.43.9
- react-native: 0.62.2
- react: 16.11.0
- react-navigation: 5.9.4

**Description/Current Behaviour**

```
        if (this.camera) {
          // Camera Take Picture Options
          const takePictureOptions = {
              quality: Platform.OS === "ios" ? 0.8 : 1,
              ...(this.state.type === RNCamera.Constants.Type.front && {
                  mirrorImage: true,
                  fixOrientation: true,
                  forceUpOrientation: true,
              }),
              orientation: 'portrait',
              pauseAfterCapture: true
          };
  
          try {
              // Take Picture
              const takePictureResponse = await this.camera.takePictureAsync(takePictureOptions);
              console.log(takePictureResponse);  // Not Working
          } catch (error) { 

          }
        }
```

**Expected Behaviour**

takePictureAsync does not resolve or reject. No line of code works after takePictureAsync. There is no error in catch.

**Steps to Reproduce**

I tried it on iPhone 7 (14.4.2) and it works fine. However, the iPhone X (14.4.2) does not do anything either.

**Comment by daimonkor** [comment]
The same bug iPhone 12 14.6
