### ISSUE TITLE
Starting video recording failed. Another recording might be in progress.

### ISSUE THREAD

**Issue by Hamza6244** [react-native-camera/react-native-camera#3240]
**To Do First**

- [x] Did you try latest release?
- [x] Did you try master?
- [x] Did you look for existing matching issues?

**Platforms**
Android

**Versions**

Android: 10
react-native-camera: 3.4.0
react-native: 0.63.4
react: 16.13.1
react-navigation: 4.0.10

**Description/Current Behaviour**
After installing the app for the first time then when I call record video function then RecordAsync throws an error
Error: Starting video recording failed. Another recording might be in progress. at createErrorFromErrorData (NativeModules.js:152) at NativeModules.js:104 at MessageQueue.__invokeCallback (MessageQueue.js:442) at MessageQueue.js:127 at MessageQueue.__guard (MessageQueue.js:343) at MessageQueue.invokeCallbackAndReturnFlushedQueue (MessageQueue.js:126) at debuggerWorker.js:80

I have all the permissions in my AndroidManifest.xml

<uses-permission android:name="android.permission.RECORD_AUDIO"/>
<uses-permission android:name="android.permission.CAMERA" />
 <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
 <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />

I am also checking all the permission before rendering the camera with react-native-permission and the response are authorized for the camera, audio, and storage.

And the second case is if I call takePictureAsync first then video function work properly

**Expected Behaviour**
It should have resolved the promise with video details like Uri, codec, etc.

**Steps to Reproduce**
Click on the start recording button after lunch the app for the very first time and call record async method it will throw an error in console.

**Sample code.**
```
startRecording = async () => {
 if (this.camera) {
      try {
        const options = {
          quality: 2,
          videoBitrate: 8000000,
          maxDuration: 30
        };
        const promise = this.camera.recordAsync(options);
        if (promise) {
          this.setState({ recording: true });
          const data = await promise;
          this.setState({ recording: false });
          console.log(data)
         }
      } catch (error) {
        console.log(error);
      }
    }
}

<RNCamera
            style={cameraStyle}
            ref={ref => {
              this.camera = ref;
            }}
            type={cameraType}
            androidCameraPermissionOptions={{
              title: 'Permission to use camera',
              message: 'We need your permission to use your camera phone',
              buttonPositive: 'Ok',
              buttonNegative: 'Cancel',
            }}
            androidRecordAudioPermissionOptions={{
              title: 'Permission to use audio recording',
              message: 'We need your permission to use your audio',
              buttonPositive: 'Ok',
              buttonNegative: 'Cancel',
            }}
           captureAudio={true}
          />
```
Thanks in advance.

**Comment by sanjaykochrekar** [comment]
I was having similar problem. I had function that start recording video. But it was called multiple times.
so I added another variable *isRecording*  to check whether camera already started recording.

if(! isRecording) {
     isRecording = true;
     startRecording();
}
