### ISSUE TITLE
Can someone use "onFacesDetected" in IOS please tell me the way.

### ISSUE THREAD

**Issue by paddypure** [react-native-camera/react-native-camera#3242]
Previously I was using "npm i react-native-camera@git+https://github.com/davidgovea/react-native-camera/tree/8c29cb1239c5f5508acf30be4094b5f27e715e8a" which made me work "onFacesDetected".
But when I updated the "Firebase" version of "12.0.0" a few days ago, I got stupid.

**Comment by renatobenks** [comment]
why don't you try to use the latest version published on npm @paddypure? Let me know what you got
