### ISSUE TITLE
> Task :react-native-camera:mergeMlkitReleaseResources FAILED

### ISSUE THREAD

**Issue by MohamedAhmed122** [react-native-camera/react-native-camera#3265]
# I am trying to build APK build and I am  facing this Error
after I run ` ./gradlew assembleRelease`
<img width="1178" alt="Screenshot 2021-06-25 at 15 09 38" src="https://user-images.githubusercontent.com/58720977/123392536-5e2abf00-d5c7-11eb-954d-cd132edbbd6d.png">

Any clue what's the problem ? , or maybe solution

**Comment by leena-sharma** [comment]
@MohamedAhmed122  
hi, did you ever solve this error?
Facing same issue , while creating release build.

**Comment by paschalidi** [comment]
+1 having the same problem at the moment. Any ideas?!

**Comment by MohamedAhmed122** [comment]
@paschalid , @leena-sharma here is the [solution](https://stackoverflow.com/questions/68139592/error-building-apk-build-error-task-apppackagerelease-failed/68139752#68139752)

**Comment by paschalidi** [comment]
True this worked for my project!
