### ISSUE TITLE
Recorded video not play on ios

### ISSUE THREAD

**Issue by suunyking1219** [react-native-camera/react-native-camera#3279]
# Bug Report

**To Do First**

- [Yes] Did you try latest release?
- [Yes] Did you try master?
- [Yes] Did you look for existing matching issues?

**Android**

**Versions**
- Android: 10.0 (Pixel 4 XL )
- iOS 14.0 (12 pro max)
- react-native-camera: 3.44.3
- react-native:0.64.2
- react:17.0.1

**Description/Current Behaviour**

Recorded video on android phone, can't play with app or browser on ios

> Love react-native-camera? Please consider supporting our collective: 👉 https://opencollective.com/react-native-camera/donate
> Want this issue to be resolved faster? Please consider adding a bounty to it https://issuehunt.io/repos/33218414

**Comment by MateusAndrade** [comment]
Maybe this is related to the encoding format, or something similar? Did it work with `vlc`?
