### ISSUE TITLE
OnBarCodeRead option slow with Code 128 when camera is closer to the barcode

### ISSUE THREAD

**Issue by hntddt123** [react-native-camera/react-native-camera#3297]
# Bug Report

**To Do First**

- [x] Did you try latest release?
- [x] Did you try master?
- [x] Did you look for existing matching issues?

**Platforms**

**Versions**

- Android: 9, 10, 11
- iOS:
- react-native-camera: 3.42.2
- react-native: 0.64.2
- react: 17
  

**Description/Current Behaviour**

Can not speed up the read speed

Slow when reading code 128
**Expected Behaviour**

A closer scan should be faster
**Steps to Reproduce**

Use OnBarCodeRead on RNCamera

**Additionals**

> Love react-native-camera? Please consider supporting our collective: 👉 https://opencollective.com/react-native-camera/donate
> Want this issue to be resolved faster? Please consider adding a bounty to it https://issuehunt.io/repos/33218414

**Comment by ajaysaini-sgvu** [comment]
I am also facing same issue. Any way to resolve this ?
