### ISSUE TITLE
With android API 30, does this library support it?

### ISSUE THREAD

**Issue by IhorFedorkiv94** [react-native-camera/react-native-camera#3304]
# Question
In 2021, we are continuing with our annual target API level update, requiring new apps to target API level 30 (Android 11) in August and in November for all app updates.
[https://android-developers.googleblog.com/2020/11/new-android-app-bundle-and-target-api.html](url)

So some methods will be **not supported**. Do you know about this?

**Comment by renatobenks** [comment]
I haven't noticed upcoming big changes that wouldn't be supported anymore so far, did you? Let us know your concerns, but for what I got, probably just a few further changes to support new versions of RN.

**Comment by IhorFedorkiv94** [comment]
Sorry for my bad explaining) 
My question is - **_react-native-camera_** lib will work fine with Android SDK  30?
Currentlly  **_react-native-camera_** lib has 29 version.


![image](https://user-images.githubusercontent.com/50927095/128320417-2bac0ba3-ad6c-48f1-b63d-4e0d9a91053f.png)

**Comment by renatobenks** [comment]
Well, I think so far I know, it will. However, this project is far from being able to make sure of anything as it has been changed a lot over the years, and was introduced so many features without any precedence, which it became very unstable. So, as standard, to make sure of it, we'll gonna have to make some tests, can you help us with?

**Comment by IhorFedorkiv94** [comment]
Thanks for your answers. Currently, I can't help with this, but if I have some information I will let you know :)

**Comment by renatobenks** [comment]
No problem! I'll try to arrange something and see how it looks likee
