### ISSUE TITLE
Should mirrorVideo: callback be invoked when errors occur?

### ISSUE THREAD

**Issue by mickmaccallum** [react-native-camera/react-native-camera#3312]
# Question

**To Do First**
- [x] Take a look in the [README](https://github.com/react-native-community/react-native-camera/blob/master/README.md)
- [x] Take a look in the [docs](https://github.com/react-native-community/react-native-camera/blob/master/docs/RNCamera.md)
- [x] Take a look in the [QA](https://github.com/react-native-community/react-native-camera/blob/master/docs/QA.md)

**Ask your Question**

I was taking a look at some of the source of this library and noticed the following code:

https://github.com/react-native-camera/react-native-camera/blob/6a2561b3169e947083afe2417c079f65eb21c16d/ios/RN/RNCamera.m#L2042-L2048

It seems that on iOS when mirroring a video, if an error occurs the callback isn't called and the promise isn't resolved. I'm not sure if this is a bug, but I just wanted to bring this to your attention in case this wasn't intentional.

**Tags**

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate
> Want this issue to be resolved faster? Please consider adding a bounty to it https://issuehunt.io/repos/33218414

**Comment by MrXyfir** [comment]
#1821
