### ISSUE TITLE
Replace jcenter() with mavenCentral()

### ISSUE THREAD

**Issue by Romick2005** [react-native-camera/react-native-camera#3334]
Add mavenCentral() as jcenter() is shutting (February 1st, 2022 JCenter will no longer be available for non-Artifactory clients).

https://github.com/react-native-camera/react-native-camera/blob/637c896762c4cf3a057a0adac8c963bc699a781b/android/build.gradle#L13

http://developer.android.com/r/tools/jcenter-end-of-service

**Comment by diegodorado** [comment]
Please reopen the issue. jcenter has been deprecated: https://docs.gradle.org/7.3.3/userguide/upgrading_version_6.html#jcenter_deprecation
