### ISSUE TITLE
onRecordingEnd is not getting called! 

### ISSUE THREAD

**Issue by akharshita** [react-native-camera/react-native-camera#3335]
# onRecordingEnd is not getting called! 

**To Do First**
The code I am using is:
`
<RNCamera
ref={(cam) => { camera.current = cam; }}
style={{
height: sWidth * (250 / 375),
overflow: 'hidden',
borderRadius: 10,
}}
onRecordingStart={() => {
console.log("recording started");
}}
onRecordingEnd={() => {
console.log("recording stopped");
}}
type={RNCamera.Constants.Type.back}
captureAudio
>
`

`
const stopcapture = () => {
		setIsRecording(false)
		if (camera) {
			camera.current.stopRecording();
		}

	}
`
`
const startCapture = async () => {
		const shouldStartCapture = () => {
			console.log("camera = ", camera.current);
				camera.current.recordAsync({
					maxDuration: 30
				})
					.then((data) => {
						setIsRecording(false)
						console.log('video capture', data);
						setRecorderData({
							recorded: true,
							recordedData: data,
							maxLength: 30,
						});
					}).catch(err => console.error("err = ", err));

		};

		if ((recorderData.maxLength > 0) || (recorderData.maxLength < 0)) {
			shouldStartCapture();
		}
	}`

**Ask your Question**

**Tags**

**Comment by jonitef** [comment]
What was the problem? I facing the same issue, onRecordingEnd not being called.
