### ISSUE TITLE
Windows: No Error/Event/Status represents "Camera is already in use"

### ISSUE THREAD

**Issue by creambyemute** [react-native-camera/react-native-camera#3337]
Hello there,

We've run into a problem while using react-native-camera for react-native-windows:
If an application (let's say the Camera App/Teams/Discord) is already using the back/front camera and you try to use same front/back camera through RNCamera you will be greeted by a black screen with a "ready" status and you also receive the onCameraReady event even though the camera is not ready.

After short digging, I suspect the `initializeAsync` should probably fire an event (onMountError, status change or idk yet) but it does not do that:
https://github.com/react-native-camera/react-native-camera/blob/master/windows/ReactNativeCameraCPP/ReactCameraView.cpp

The Camera App on windows on the other hand does greet us with a black screen as well, but an error message is shown that the device is already in use.

Repro steps:
* Init project with RNCamera + React-Native-Windows
* Open Windows Camera App
* Open RNApp which should show the camera
* Black screen is shown with no error message/corresponding event/status change

I tried the same on an Samsung Tablet with Android 11 with split-apps and under Android the camera app will pause and the RNCamera in the App gets activated.

**Comment by GodVampire** [comment]
still
