### ISSUE TITLE
Only crashing even with examples basic code I am using !!!

### ISSUE THREAD

**Issue by joy-mollick** [react-native-camera/react-native-camera#3376]
I just wanted to extract text . But detect text crashes app without any error . I uses basic examples code from example folder .

 "dependencies": {
    "@react-native-community/slider": "^4.1.10",
    "react": "17.0.2",
    "react-native": "0.66.1",
    "react-native-camera": "^4.2.1"
  },

Anyone  urgently here plz help me to pull this off ???

**Comment by yoakim** [comment]
Hello!

I had some crashes when i bumped my RNC to 4.2.1 (from 3.x.x).

Here are the changes i made in my repo to get it working:

_android/app/build.gradle_ 
+`missingDimensionStrategy 'react-native-camera', 'mlkit'`
-`missingDimensionStrategy 'react-native-camera', 'general'`

+`apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)`
+`apply plugin: 'com.google.android.gms.strict-version-matcher-plugin'`
-`apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)`

_android/build.gradle_
+`classpath("com.android.tools.build:gradle:4.1.0", "com.google.android.gms:strict-version-matcher-plugin:1.2.1")`
-`classpath("com.android.tools.build:gradle:4.1.0")`
