### ISSUE TITLE
Android stretches horizontally when recording

### ISSUE THREAD

**Issue by JonnyLinja** [react-native-camera/react-native-camera#869]
The camera looks fine at first. Once recording begins, it gets stretched horizontally. Once you end recording though, the file itself is NOT stretched.

I do not have this issue with iOS.

**Comment by wilonth** [comment]
Such a major issue, why is there no attention?

**Comment by murtuzamac** [comment]
Same issue here. But in my case, the camera is stretched vertically. I tried to set different "ratio" property of the <RNCamera> but still, it is getting stretched.

**Comment by billouboq** [comment]
Any new on this ? Having ratio issues too on Android

**Comment by billouboq** [comment]
Still have the issue

**Comment by ShawalAhmadPF** [comment]
Still have issue....:pensive:
